#![feature(rustc_attrs)]
#![allow(internal_features)] // class/ctor/virtual attrs ride rustc_attrs
#![allow(dead_code)]

//! A Rust `class` that subclasses an *imported* C++ polymorphic base
//! **with a virtual destructor**.
//!
//! `CppBase` is generated by `cxx_importer` from `cpp/cppbase.hpp`
//! (see `gen_bindings.rs`); the generated `#[rustc_cxx_imported_vtable]`
//! attribute (carrying `vdtor=1`) lets rustcc extend the C++ vtable —
//! virtual *methods* and the virtual *destructor*. C++ dispatching a
//! virtual through a `CppBase*` that points at a `MyWidget` lands in the
//! Rust `override`; `delete (CppBase*)widget` runs the Rust `Drop`,
//! destroys the base subobject, and frees — exactly once.
//!
//! Because C++ owns and `delete`s the object, the factory allocates it
//! through the C++ allocator (`operator new` + placement-construct);
//! the vtable's deleting destructor reclaims it with `operator delete`.

include!("../target/gen-out/bindings.rs");

unsafe extern "C++" {
    #[link_name = "_Znwm"] // C++ operator new(size_t)
    fn cxx_operator_new(size: usize) -> *mut u8;
}

unsafe extern "C" {
    fn note_derived_drop(); // test counter (defined in caller.cpp)
}

pub class MyWidget : CppBase {
    extra: i32,

    pub constructor fn new(x: i32, extra: i32) -> Self {
        // `CppBase::new` runs the C++ base-object ctor (C2) into `__base`;
        // rustcc overwrites the vptr with MyWidget's vtable at ctor end.
        MyWidget { __base: CppBase::new(x), extra }
    }

    pub override fn foo(&self) -> i32 {
        self.extra + 100
    }

    pub override fn describe(&self) -> i32 {
        self.extra + 200
    }

    pub virtual fn only_mine(&self) -> i32 {
        self.extra * 3
    }
}

// Runs when the object is destroyed — including via C++ `delete` through
// a `CppBase*`. Dropping `self` also drops the `__base` subobject, whose
// `Drop` runs the C++ base destructor.
impl Drop for MyWidget {
    fn drop(&mut self) {
        unsafe { note_derived_drop() }
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn make_widget(x: i32, extra: i32) -> *mut MyWidget {
    unsafe {
        let p = cxx_operator_new(core::mem::size_of::<MyWidget>()) as *mut MyWidget;
        p.write(MyWidget::new(x, extra));
        p
    }
}
