#![feature(rustc_attrs)]
#![allow(internal_features)] // class/ctor/virtual attrs ride rustc_attrs
#![allow(dead_code)]

//! A Rust `class` that subclasses an *imported* C++ polymorphic base.
//!
//! `CppBase` is generated by `cxx_importer` from `cpp/cppbase.hpp`
//! (see `gen_bindings.rs`); the generated `#[rustc_cxx_imported_vtable]`
//! attribute lets rustcc extend the C++ vtable. C++ dispatching a
//! virtual through a `CppBase*` that actually points at a `MyWidget`
//! lands in the Rust `override` — the same way C++-native virtual
//! dispatch would. Compiled with the rustcc fork `rustc` (for the
//! `class` keyword + `extern "C++"`).

// The importer's output: the `#[repr(C)]` `CppBase` struct carrying
// `#[rustc_cxx_imported_vtable = "…"]`, its `extern "C++"` decls, and
// safe wrappers. Regenerate with `cargo run --bin gen_bindings --release`.
// Path is relative to this source file (we compile with bare `rustc`,
// so `CARGO_MANIFEST_DIR` isn't set).
include!("../target/gen-out/bindings.rs");

pub class MyWidget : CppBase {
    extra: i32,

    pub constructor fn new(x: i32, extra: i32) -> Self {
        // `CppBase::new` runs the C++ base-object ctor (C2) into the
        // `__base` subobject; rustcc then overwrites the vptr with
        // MyWidget's vtable at the end of this ctor.
        MyWidget { __base: CppBase::new(x), extra }
    }

    // Overrides the *concrete* base virtual `foo` (slot 0).
    pub override fn foo(&self) -> i32 {
        self.extra + 100
    }

    // Overrides the *pure* base virtual `describe` (slot 1) — this is
    // the abstract-base / FLTK `handle()`-style case.
    pub override fn describe(&self) -> i32 {
        self.extra + 200
    }

    // A brand-new virtual not present in CppBase (appended at slot 2).
    pub virtual fn only_mine(&self) -> i32 {
        self.extra * 3
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn make_widget(x: i32, extra: i32) -> *mut MyWidget {
    Box::into_raw(Box::new(MyWidget::new(x, extra)))
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn free_widget(w: *mut MyWidget) {
    if !w.is_null() {
        unsafe { drop(Box::from_raw(w)) };
    }
}
