
//! A Rust `class` that subclasses the **deepest** level of an *imported*
//! C++ inheritance chain (`Widget : Drawable : Shape`) and overrides
//! virtuals introduced at **every** level of that chain.
//!
//! `Shape`/`Drawable`/`Widget` are generated by `cxx_importer` from
//! `cpp/cppbase.hpp` (see `gen_bindings.rs`). The importer flattens the
//! full primary vtable into a single `#[rustc_cxx_imported_vtable]`
//! attribute on `Widget` — every inherited slot, with the right
//! override-matching name and final-overrider symbol — so rustcc can
//! extend the C++ vtable across the whole chain.
//!
//! Cross-boundary behavior this demonstrates:
//!   * C++ dispatching `area()` through a `Shape*` (the grandparent, two
//!     levels up) lands in the Rust `override fn area`.
//!   * Likewise `z_order()` via `Drawable*` and `handle()` via `Widget*`.
//!   * `delete (Shape*)widget` runs the Rust `Drop`, then the full C++
//!     destructor chain (`~Widget`/`~Drawable`/`~Shape`), then frees —
//!     each exactly once (the `Shape` root has a virtual destructor).
//!
//! Because C++ owns and `delete`s the object, the factory allocates it
//! through the C++ allocator (`operator new` + placement-construct); the
//! vtable's deleting destructor reclaims it with `operator delete`.

include!("../target/gen-out/bindings.rs");

unsafe extern "C++" {
    #[link_name = "_Znwm"] // C++ operator new(size_t)
    fn cxx_operator_new(size: usize) -> *mut u8;
}

unsafe extern "C" {
    fn note_derived_drop(); // test counter (defined in caller.cpp)
}

pub class MyWidget : Widget {
    extra: i32,

    pub constructor fn new(x: i32, extra: i32) -> Self {
        // `Widget::new` runs the C++ ctor chain (Shape -> Drawable ->
        // Widget) into `__base`; rustcc overwrites the vptr with
        // MyWidget's vtable at ctor end.
        MyWidget { __base: Widget::new(x), extra }
    }

    // Override a virtual at each level of the imported chain:
    pub override fn area(&self) -> i32 { self.extra + 1000 }    // Shape    (grandparent)
    pub override fn z_order(&self) -> i32 { self.extra + 2000 } // Drawable (parent)
    pub override fn handle(&self) -> i32 { self.extra + 3000 }  // Widget   (direct base)

    pub virtual fn only_mine(&self) -> i32 { self.extra }       // new slot on MyWidget
}

// Runs when the object is destroyed — including via C++ `delete` through
// any base pointer in the chain. Dropping `self` also drops the `__base`
// subobject, whose `Drop` runs the C++ destructor chain.
impl Drop for MyWidget {
    fn drop(&mut self) {
        unsafe { note_derived_drop() }
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn make_widget(x: i32, extra: i32) -> *mut MyWidget {
    unsafe {
        let p = cxx_operator_new(core::mem::size_of::<MyWidget>()) as *mut MyWidget;
        p.write(MyWidget::new(x, extra));
        p
    }
}
