//! `.hpp` emitter for Rust `#[repr(cpp)]` types.
//!
//! Implements the "C++ sees a Rust type" direction from
//! `docs/repr_cpp.md §3`: for every class in the IR, emit a C++ class
//! declaration whose public section lists the user's methods and whose
//! private section is an opaque, correctly-aligned storage blob sized
//! from `rustc_abi_cxx::layout`. The body of every method is elsewhere
//! (a rustc-emitted object with Itanium mangling); the header only
//! needs to supply declarations.
//!
//! Scope for v1:
//! - Single class per emit call, or a list that share the same header.
//! - Methods: identifier-named, non-virtual.
//! - Always emits: deleted copy-ctor, `noexcept` move-ctor, dtor.
//! - Ctors declared on the class (default, `OtherCtor`) are emitted as
//!   `ClassName(params)`; user-declared copy/move/dtor are shadowed by
//!   the always-emitted set.
//! - Parameters & return types: scalar builtins (rendered with
//!   `<cstdint>` fixed-width names), pointers/references, and record
//!   types by value. Arrays, function types, member pointers: not yet.
//! - `virtual` methods are skipped (the vtable-generation story is v1.5
//!   per `docs/repr_cpp.md §5`).
//! - Operator and conversion-function names are skipped for v1 — the
//!   mangling works but the `.hpp` rendering for operators requires
//!   care (e.g. `operator+` as a member vs. free function) that isn't
//!   worth designing before a user asks for it.

use std::fmt::Write as _;

use rustc_abi_cxx::{
    ClassId, CvQual, CxxType, CxxTypeCtx, FloatKind, IntWidth, LayoutError,
    MethodDef, NameSegment, NestedName, RefKind, SpecialMember, TemplateArg,
    TypeId, Virtuality,
};

#[derive(Debug, Clone)]
pub enum HppError {
    Layout(LayoutError),
    UnsupportedType { where_: String, kind: String },
}

impl From<LayoutError> for HppError {
    fn from(e: LayoutError) -> Self {
        Self::Layout(e)
    }
}

impl core::fmt::Display for HppError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{self:?}")
    }
}

impl std::error::Error for HppError {}

pub struct HppOptions<'a> {
    /// The classes to expose to C++. Each class's layout is computed via
    /// `CxxTypeCtx::layout` to produce its opaque storage declaration.
    pub classes: &'a [ClassId],
}

/// Convenience wrapper around `generate_hpp` that pulls the class list
/// straight from `ctx.rust_classes()` and also emits every registered
/// Rust-origin enum at the top of the file. This is the form drivers
/// should use in the normal "expose every `#[repr(cpp)]` type in the
/// crate" path — manual class selection is only useful for tests and
/// advanced cases (e.g., splitting a crate's types across several
/// headers).
pub fn generate_hpp_for_rust_types(
    ctx: &CxxTypeCtx,
) -> Result<String, HppError> {
    let classes: Vec<ClassId> = ctx.rust_classes().collect();
    let mut out = generate_hpp(ctx, &HppOptions { classes: &classes })?;
    // Enums come after classes so struct declarations never depend
    // on a forward enum declaration — scoped enums don't interact
    // with class layouts in v1 anyway.
    for enum_id in ctx.rust_enum_ids() {
        out.push('\n');
        out.push_str(&render_rust_enum(ctx, enum_id)?);
    }
    Ok(out)
}

fn render_rust_enum(
    ctx: &CxxTypeCtx,
    enum_id: rustc_abi_cxx::RustEnumId,
) -> Result<String, HppError> {
    let e = ctx.rust_enum(enum_id);
    let underlying = render_type(ctx, e.underlying, "enum underlying")?;
    let mut out = String::new();
    let _ = writeln!(out, "enum class {} : {} {{", e.cpp_name, underlying);
    for v in &e.variants {
        match v.discriminant {
            Some(d) => {
                let _ = writeln!(out, "    {} = {},", v.name, d);
            }
            None => {
                let _ = writeln!(out, "    {},", v.name);
            }
        }
    }
    out.push_str("};\n");
    Ok(out)
}

pub fn generate_hpp(
    ctx: &CxxTypeCtx,
    opts: &HppOptions<'_>,
) -> Result<String, HppError> {
    let mut out = String::new();
    out.push_str(
        "// Generated by rustcc cxx_importer::hpp. Do not hand-edit.\n\
         // See docs/repr_cpp.md for the shape of this file.\n\n\
         #pragma once\n\
         #include <cstdint>\n\n",
    );

    for &class_id in opts.classes {
        let class = ctx.class(class_id);
        let layout = ctx.layout(class_id)?;

        // Split the NestedName: everything before the last segment is
        // the namespace chain; the last segment is the class name. We
        // don't support nested class declarations (`Outer::Inner`) in
        // the v1 `.hpp` emitter — users of nested types get a flat name
        // with `::` still spelled into the mangled symbol (so calls
        // still wire up) but the C++ declaration sits in the namespace.
        let (namespaces, class_name) = split_nested_name(&class.name)?;
        let indent = "    ";

        let mut ns_depth = 0usize;
        for ns in &namespaces {
            let _ = writeln!(out, "namespace {ns} {{");
            ns_depth += 1;
        }
        if ns_depth > 0 {
            out.push('\n');
        }

        let _ = writeln!(out, "class {class_name} {{");
        out.push_str("public:\n");

        // User-declared constructors (excluding copy/move which we shadow).
        for method in &class.methods {
            if method.virtuality != Virtuality::NonVirtual {
                continue;
            }
            match method.special {
                Some(SpecialMember::DefaultCtor)
                | Some(SpecialMember::OtherCtor) => {
                    let params = render_params(ctx, &method.sig.params)?;
                    let _ = writeln!(
                        out,
                        "{indent}{class_name}({params});"
                    );
                }
                _ => {}
            }
        }

        // Always-emitted special members (§3 of repr_cpp.md).
        let _ = writeln!(
            out,
            "{indent}{class_name}(const {class_name}&) = delete;"
        );
        let _ = writeln!(
            out,
            "{indent}{class_name}({class_name}&&) noexcept;"
        );
        let _ = writeln!(out, "{indent}~{class_name}();");

        // User-declared non-special, non-virtual methods with ident names.
        let mut any_user_method = false;
        for method in &class.methods {
            if method.virtuality != Virtuality::NonVirtual {
                continue;
            }
            if method.special.is_some() {
                continue;
            }
            let Some(name) = method.name.ident_name() else {
                continue;
            };
            if !any_user_method {
                out.push('\n');
                any_user_method = true;
            }
            let sig = render_method_signature(ctx, method, name, indent)?;
            out.push_str(&sig);
        }

        // Opaque storage. The `alignas` value and array size come
        // straight from the computed layout, so any `#[repr(cpp)]`
        // type change that shifts size/align regenerates this header
        // with new numbers. C++ can't peek inside or rearrange fields.
        out.push_str("\nprivate:\n");
        let _ = writeln!(
            out,
            "{indent}alignas({}) unsigned char __rust_storage[{}];",
            layout.align_bytes.max(1),
            layout.size_bytes
        );

        out.push_str("};\n");

        for ns in namespaces.iter().rev() {
            let _ = writeln!(out, "}}  // namespace {ns}");
        }
        if ns_depth > 0 {
            out.push('\n');
        }
    }

    Ok(out)
}

fn render_method_signature(
    ctx: &CxxTypeCtx,
    method: &MethodDef,
    name: &str,
    indent: &str,
) -> Result<String, HppError> {
    let ret = render_type(ctx, method.sig.ret, "return type")?;
    let params = render_params(ctx, &method.sig.params)?;
    let cv = if method.sig.cv.is_const { " const" } else { "" };
    let mut out = String::new();
    let _ = writeln!(out, "{indent}{ret} {name}({params}){cv};");
    Ok(out)
}

fn render_params(
    ctx: &CxxTypeCtx,
    params: &[TypeId],
) -> Result<String, HppError> {
    let mut pieces = Vec::with_capacity(params.len());
    for (i, p) in params.iter().enumerate() {
        let ty = render_type(ctx, *p, "parameter")?;
        pieces.push(format!("{ty} arg{i}"));
    }
    Ok(pieces.join(", "))
}

fn render_type(
    ctx: &CxxTypeCtx,
    ty: TypeId,
    where_: &str,
) -> Result<String, HppError> {
    let t = ctx.type_of(ty);
    match t {
        CxxType::Void => Ok("void".to_string()),
        CxxType::Bool => Ok("bool".to_string()),
        CxxType::Int { signed, width } => {
            Ok(int_stdint(*signed, *width).to_string())
        }
        CxxType::Float { kind } => Ok(match kind {
            FloatKind::F32 => "float".to_string(),
            FloatKind::F64 => "double".to_string(),
            FloatKind::LongDouble => "long double".to_string(),
        }),
        CxxType::Ptr { pointee, cv } => {
            let inner = render_type(ctx, *pointee, where_)?;
            Ok(apply_cv_prefix(&inner, *cv) + "*")
        }
        CxxType::Ref { pointee, kind, cv } => {
            let inner = render_type(ctx, *pointee, where_)?;
            let sigil = match kind {
                RefKind::Lvalue => "&",
                RefKind::Rvalue => "&&",
            };
            Ok(apply_cv_prefix(&inner, *cv) + sigil)
        }
        CxxType::Record(class_id) => {
            render_nested_name(&ctx.class(*class_id).name)
        }
        CxxType::Enum { name, .. } => render_nested_name(name),
        CxxType::Array { .. }
        | CxxType::Fn(_)
        | CxxType::MemberPtr { .. } => Err(HppError::UnsupportedType {
            where_: where_.to_string(),
            kind: format!("{t:?}"),
        }),
    }
}

fn int_stdint(signed: bool, width: IntWidth) -> &'static str {
    match (signed, width) {
        (true, IntWidth::I8) => "std::int8_t",
        (false, IntWidth::I8) => "std::uint8_t",
        (true, IntWidth::I16) => "std::int16_t",
        (false, IntWidth::I16) => "std::uint16_t",
        (true, IntWidth::I32) => "std::int32_t",
        (false, IntWidth::I32) => "std::uint32_t",
        // `long long` / `unsigned long long` rather than
        // `std::int64_t` / `std::uint64_t`: the typedef under
        // <cstdint> is platform-specific (macOS makes it `long
        // long`, Linux makes it `long`), which causes the mangled
        // symbol C++ produces to disagree with what `rustc_abi_cxx`
        // emits for i64/u64. Writing the primitive types
        // explicitly sidesteps the ambiguity.
        (true, IntWidth::I64) => "long long",
        (false, IntWidth::I64) => "unsigned long long",
        (true, IntWidth::I128) => "__int128",
        (false, IntWidth::I128) => "unsigned __int128",
    }
}

fn apply_cv_prefix(inner: &str, cv: CvQual) -> String {
    let mut out = String::new();
    if cv.is_const {
        out.push_str("const ");
    }
    if cv.is_volatile {
        out.push_str("volatile ");
    }
    out.push_str(inner);
    out
}

fn render_nested_name(name: &NestedName) -> Result<String, HppError> {
    let mut parts = Vec::with_capacity(name.0.len());
    for seg in &name.0 {
        parts.push(render_segment(seg)?);
    }
    Ok(parts.join("::"))
}

fn render_segment(seg: &NameSegment) -> Result<String, HppError> {
    match seg {
        NameSegment::Namespace(i)
        | NameSegment::Class(i)
        | NameSegment::Enum(i) => Ok(i.0.clone()),
        NameSegment::AnonymousNamespace => Ok("/* anon */".to_string()),
        NameSegment::TemplateSpec { name, args } => {
            let mut arg_srcs = Vec::with_capacity(args.len());
            for arg in args {
                match arg {
                    TemplateArg::Type(_ty) => {
                        // Template args in .hpp output aren't
                        // round-trippable without a full type printer;
                        // for v1 emit a placeholder so users notice.
                        arg_srcs.push("/* arg */".to_string());
                    }
                }
            }
            Ok(format!("{}<{}>", name.0, arg_srcs.join(", ")))
        }
    }
}

/// Split `NestedName` into (namespaces..., class-name). Errors if the
/// name doesn't end in a Class/Enum segment.
fn split_nested_name(
    name: &NestedName,
) -> Result<(Vec<String>, String), HppError> {
    let (last, prefix) = name.0.split_last().ok_or_else(|| {
        HppError::UnsupportedType {
            where_: "class name".to_string(),
            kind: "empty NestedName".to_string(),
        }
    })?;
    let class_name = match last {
        NameSegment::Class(i) | NameSegment::Enum(i) => i.0.clone(),
        NameSegment::TemplateSpec { name, .. } => name.0.clone(),
        _ => {
            return Err(HppError::UnsupportedType {
                where_: "class name".to_string(),
                kind: format!("last segment {last:?} is not a class"),
            });
        }
    };
    let mut namespaces = Vec::new();
    for seg in prefix {
        match seg {
            NameSegment::Namespace(i) => namespaces.push(i.0.clone()),
            _ => {
                return Err(HppError::UnsupportedType {
                    where_: "enclosing scope".to_string(),
                    kind: format!("non-namespace segment {seg:?}"),
                });
            }
        }
    }
    Ok((namespaces, class_name))
}

