//! C++ stub bodies for Rust-side `#[repr(cpp)]` methods.
//!
//! # Purpose
//!
//! The generated `.hpp` (see [`crate::hpp`]) declares Rust-authored
//! methods with normal C++ member signatures. Those declarations need
//! definitions at link time. Once the rustc fork is emitting Itanium-
//! mangled object code, it supplies them directly. Until then, this
//! module emits a parallel `.cpp` file whose definitions `abort()`
//! with a descriptive message. Consumers can therefore compile **and
//! link** against the generated header today, trading silent UB for a
//! loud runtime failure when a method that has no Rust body yet is
//! invoked.
//!
//! The emitted bodies are strictly placeholders. They:
//!
//! - Cover every method the `.hpp` declares — user methods, always-
//!   emitted move ctor, always-emitted dtor, user-declared ctors.
//! - Use `[[noreturn]]` to tell Clang the surrounding function never
//!   returns, sidestepping the "value must be returned" rule for
//!   non-trivially-constructible return types.
//! - Emit a `std::fprintf` to stderr with the symbol name before
//!   `std::abort()` so crash logs explain themselves.
//!
//! # Scope for v1
//!
//! Same subset the `.hpp` emitter supports: identifier-named non-
//! virtual methods, POD-ish records, scalar params/returns. Operator
//! and conversion-function methods are skipped in parallel with the
//! emitter.

use std::fmt::Write as _;

use rustc_abi_cxx::{
    ClassId, CxxType, CxxTypeCtx, FloatKind, IntWidth, MethodDef, NameSegment,
    NestedName, RefKind, RecordKind, CvQual, SpecialMember, TemplateArg,
    TypeId, TypeOrigin, Virtuality,
};

#[derive(Debug)]
pub enum StubError {
    UnsupportedType { where_: String, kind: String },
}

impl core::fmt::Display for StubError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{self:?}")
    }
}

impl std::error::Error for StubError {}

/// Emit a single `.cpp` source containing stub bodies for every Rust-
/// origin class's method. Callers typically write the result to
/// `<crate>-cxx-stubs.cpp` and compile it alongside the `.hpp`-
/// consuming C++ code.
///
/// `header_include` is the relative path users should `#include` at
/// the top of the emitted file — usually the generated `.hpp`'s file
/// name (e.g., `"mycrate-cxx.hpp"`). Paths are emitted verbatim into
/// a `#include "..."` directive, so shell-quoting rules apply.
pub fn generate_rust_stub_shims(
    ctx: &CxxTypeCtx,
    header_include: &str,
) -> Result<String, StubError> {
    let mut out = String::new();
    out.push_str(
        "// Generated by rustcc cxx_importer::rust_stubs. Do not hand-edit.\n\
         // Pre-fork stub bodies — every call aborts with a descriptive\n\
         // message. Replace by linking against the rustc-fork object.\n\n",
    );
    let _ = writeln!(out, "#include \"{header_include}\"");
    out.push_str(
        "#include <cstdio>\n\
         #include <cstdint>\n\
         #include <cstdlib>\n\n\
         namespace { [[noreturn]] void __rustcc_stub(const char* sym) {\n\
         \x20\x20\x20\x20std::fprintf(stderr, \"rustcc: call to %s — rustc fork codegen missing\\n\", sym);\n\
         \x20\x20\x20\x20std::abort();\n\
         } }\n\n",
    );

    for class_id in ctx.rust_classes() {
        emit_class_stubs(&mut out, ctx, class_id)?;
    }

    Ok(out)
}

fn emit_class_stubs(
    out: &mut String,
    ctx: &CxxTypeCtx,
    class_id: ClassId,
) -> Result<(), StubError> {
    let class = ctx.class(class_id);
    debug_assert_eq!(ctx.class_origin(class_id), TypeOrigin::RustReprCpp);
    if class.kind == RecordKind::Union {
        // Unions aren't exposed in the v1 .hpp emitter — skip here too
        // rather than emitting orphan bodies that won't link.
        return Ok(());
    }

    let (namespaces, class_name) = split_class_name(&class.name)?;
    let qualified = if namespaces.is_empty() {
        class_name.clone()
    } else {
        format!("{}::{}", namespaces.join("::"), class_name)
    };

    let mut open_ns = String::new();
    let mut close_ns = String::new();
    for ns in &namespaces {
        writeln!(open_ns, "namespace {ns} {{").ok();
        writeln!(close_ns, "}}  // namespace {ns}").ok();
    }
    if !namespaces.is_empty() {
        out.push_str(&open_ns);
        out.push('\n');
    }

    // Always-emitted special members (move ctor + dtor), matching
    // hpp.rs's canonical set.
    let _ = writeln!(
        out,
        "{class_name}::{class_name}({class_name}&&) noexcept {{ __rustcc_stub(\"{qualified}::{class_name}({class_name}&&)\"); }}",
    );
    let _ = writeln!(
        out,
        "{class_name}::~{class_name}() {{ __rustcc_stub(\"{qualified}::~{class_name}\"); }}",
    );

    for method in &class.methods {
        if method.virtuality != Virtuality::NonVirtual {
            continue;
        }
        // User-declared copy/move/dtor are shadowed by the canonical
        // set we emitted above; don't duplicate them.
        if matches!(
            method.special,
            Some(SpecialMember::CopyCtor)
                | Some(SpecialMember::MoveCtor)
                | Some(SpecialMember::Dtor)
                | Some(SpecialMember::CopyAssign)
                | Some(SpecialMember::MoveAssign)
        ) {
            continue;
        }
        let body = render_method_stub(
            ctx,
            &qualified,
            &class_name,
            method,
        )?;
        out.push_str(&body);
    }

    if !namespaces.is_empty() {
        out.push('\n');
        out.push_str(&close_ns);
    }
    out.push('\n');
    Ok(())
}

fn render_method_stub(
    ctx: &CxxTypeCtx,
    qualified: &str,
    class_name: &str,
    method: &MethodDef,
) -> Result<String, StubError> {
    let name = match method.name.ident_name() {
        Some(n) => n,
        None => return Ok(String::new()), // operators / conversions: skip (parallel with hpp)
    };
    let params = render_params(ctx, &method.sig.params, "param")?;
    let cv_suffix = cv_suffix(&method.sig.cv);

    // Constructors: no return type.
    let is_ctor = matches!(
        method.special,
        Some(SpecialMember::DefaultCtor) | Some(SpecialMember::OtherCtor)
    );
    if is_ctor {
        return Ok(format!(
            "{class_name}::{class_name}({params}){cv_suffix} {{ __rustcc_stub(\"{qualified}::{name}\"); }}\n",
        ));
    }

    let ret = render_type(ctx, method.sig.ret, "return")?;
    Ok(format!(
        "{ret} {class_name}::{name}({params}){cv_suffix} {{ __rustcc_stub(\"{qualified}::{name}\"); }}\n",
    ))
}

fn cv_suffix(cv: &CvQual) -> String {
    let mut s = String::new();
    if cv.is_const {
        s.push_str(" const");
    }
    if cv.is_volatile {
        s.push_str(" volatile");
    }
    s
}

fn render_params(
    ctx: &CxxTypeCtx,
    params: &[TypeId],
    prefix: &str,
) -> Result<String, StubError> {
    let mut out = Vec::with_capacity(params.len());
    for (i, p) in params.iter().enumerate() {
        let ty = render_type(ctx, *p, "parameter")?;
        out.push(format!("{ty} {prefix}{i}"));
    }
    Ok(out.join(", "))
}

fn render_type(
    ctx: &CxxTypeCtx,
    ty: TypeId,
    where_: &str,
) -> Result<String, StubError> {
    match ctx.type_of(ty) {
        CxxType::Void => Ok("void".to_string()),
        CxxType::Bool => Ok("bool".to_string()),
        CxxType::Int { signed, width } => Ok(int_stdint(*signed, *width).to_string()),
        CxxType::Float { kind } => Ok(match kind {
            FloatKind::F32 => "float".into(),
            FloatKind::F64 => "double".into(),
            FloatKind::LongDouble => "long double".into(),
        }),
        CxxType::Ptr { pointee, cv } => {
            let inner = render_type(ctx, *pointee, where_)?;
            Ok(cv_prefix(&inner, *cv) + "*")
        }
        CxxType::Ref { pointee, kind, cv } => {
            let inner = render_type(ctx, *pointee, where_)?;
            let sigil = match kind {
                RefKind::Lvalue => "&",
                RefKind::Rvalue => "&&",
            };
            Ok(cv_prefix(&inner, *cv) + sigil)
        }
        CxxType::Record(id) => render_nested_name(&ctx.class(*id).name),
        CxxType::Enum { name, .. } => render_nested_name(name),
        CxxType::Array { .. }
        | CxxType::Fn(_)
        | CxxType::MemberPtr { .. } => Err(StubError::UnsupportedType {
            where_: where_.to_string(),
            kind: format!("{:?}", ctx.type_of(ty)),
        }),
    }
}

fn cv_prefix(inner: &str, cv: CvQual) -> String {
    let mut out = String::new();
    if cv.is_const {
        out.push_str("const ");
    }
    if cv.is_volatile {
        out.push_str("volatile ");
    }
    out.push_str(inner);
    out
}

fn int_stdint(signed: bool, width: IntWidth) -> &'static str {
    match (signed, width) {
        (true, IntWidth::I8) => "std::int8_t",
        (false, IntWidth::I8) => "std::uint8_t",
        (true, IntWidth::I16) => "std::int16_t",
        (false, IntWidth::I16) => "std::uint16_t",
        (true, IntWidth::I32) => "std::int32_t",
        (false, IntWidth::I32) => "std::uint32_t",
        (true, IntWidth::I64) => "long long",
        (false, IntWidth::I64) => "unsigned long long",
        (true, IntWidth::I128) => "__int128",
        (false, IntWidth::I128) => "unsigned __int128",
    }
}

fn render_nested_name(name: &NestedName) -> Result<String, StubError> {
    let mut parts = Vec::with_capacity(name.0.len());
    for seg in &name.0 {
        parts.push(match seg {
            NameSegment::Namespace(i)
            | NameSegment::Class(i)
            | NameSegment::Enum(i) => i.0.clone(),
            NameSegment::AnonymousNamespace => "/* anon */".into(),
            NameSegment::TemplateSpec { name, args } => {
                let mut a = Vec::with_capacity(args.len());
                for arg in args {
                    match arg {
                        TemplateArg::Type(_) => a.push("/* arg */".to_string()),
                        TemplateArg::Integral { value, .. } => {
                            a.push(value.to_string())
                        }
                        TemplateArg::Template(nested) => a.push(
                            nested
                                .0
                                .iter()
                                .filter_map(|s| match s {
                                    NameSegment::Namespace(i)
                                    | NameSegment::Class(i)
                                    | NameSegment::Enum(i) => {
                                        Some(i.0.as_str())
                                    }
                                    _ => None,
                                })
                                .collect::<Vec<_>>()
                                .join("::"),
                        ),
                    }
                }
                format!("{}<{}>", name.0, a.join(", "))
            }
        });
    }
    Ok(parts.join("::"))
}

fn split_class_name(
    name: &NestedName,
) -> Result<(Vec<String>, String), StubError> {
    let (last, prefix) = name.0.split_last().ok_or_else(|| StubError::UnsupportedType {
        where_: "class name".into(),
        kind: "empty NestedName".into(),
    })?;
    let class_name = match last {
        NameSegment::Class(i) | NameSegment::Enum(i) => i.0.clone(),
        NameSegment::TemplateSpec { name, .. } => name.0.clone(),
        _ => {
            return Err(StubError::UnsupportedType {
                where_: "class name".into(),
                kind: format!("{last:?}"),
            });
        }
    };
    let mut namespaces = Vec::new();
    for seg in prefix {
        match seg {
            NameSegment::Namespace(i) => namespaces.push(i.0.clone()),
            other => {
                return Err(StubError::UnsupportedType {
                    where_: "enclosing scope".into(),
                    kind: format!("non-namespace segment {other:?}"),
                });
            }
        }
    }
    Ok((namespaces, class_name))
}

#[cfg(test)]
mod tests {
    use super::*;
    use rustc_abi_cxx::{
        ClassDef, CxxType, FieldDef, FnSig, Ident, MethodDef, MethodName,
        RecordKind, Target, Virtuality,
    };

    fn ctx_with_point() -> (CxxTypeCtx, ClassId) {
        let mut ctx = CxxTypeCtx::new(Target::x86_64_apple_darwin());
        let i32_ = ctx.intern_type(CxxType::Int { signed: true, width: IntWidth::I32 });
        let void_ = ctx.intern_type(CxxType::Void);
        let id = ctx.define_rust_class(ClassDef {
            name: NestedName(vec![NameSegment::Class(Ident("Point".into()))]),
            bases: vec![],
            fields: vec![
                FieldDef { name: Ident("x".into()), ty: i32_, explicit_align: None },
                FieldDef { name: Ident("y".into()), ty: i32_, explicit_align: None },
            ],
            methods: vec![
                // User ctor Foo(i32, i32)
                MethodDef { access: Default::default(),
                    name: MethodName::Ident(Ident("Point".into())),
                    sig: FnSig {
                        params: vec![i32_, i32_],
                        ret: void_,
                        cv: CvQual::default(),
                        ref_q: None,
                        variadic: false,
                        noexcept: true,
                    },
                    virtuality: Virtuality::NonVirtual,
                    vtable_index: None,
                    special: Some(SpecialMember::OtherCtor),
                },
                MethodDef { access: Default::default(),
                    name: MethodName::Ident(Ident("magnitude_sq".into())),
                    sig: FnSig {
                        params: vec![],
                        ret: i32_,
                        cv: CvQual { is_const: true, is_volatile: false },
                        ref_q: None,
                        variadic: false,
                        noexcept: true,
                    },
                    virtuality: Virtuality::NonVirtual,
                    vtable_index: None,
                    special: None,
                },
            ],
            kind: RecordKind::Struct,
            is_polymorphic: false,
            is_final: false,
            source_alignment: None,
        });
        (ctx, id)
    }

    #[test]
    fn emits_move_ctor_dtor_user_ctor_and_method_bodies() {
        let (ctx, _id) = ctx_with_point();
        let out = generate_rust_stub_shims(&ctx, "mycrate-cxx.hpp").unwrap();

        assert!(out.contains("#include \"mycrate-cxx.hpp\""));
        // Move ctor stub.
        assert!(
            out.contains("Point::Point(Point&&) noexcept {"),
            "missing move ctor body: {out}"
        );
        // Dtor stub.
        assert!(
            out.contains("Point::~Point() {"),
            "missing dtor body: {out}"
        );
        // User ctor stub with i32 params.
        assert!(
            out.contains("Point::Point(std::int32_t param0, std::int32_t param1)"),
            "missing user ctor body: {out}"
        );
        // User method stub with const qualifier and i32 return.
        assert!(
            out.contains("std::int32_t Point::magnitude_sq() const {"),
            "missing method body: {out}"
        );
        // Every body routes through the abort helper.
        assert!(out.contains("__rustcc_stub("));
    }

    #[test]
    fn namespace_open_close_matches_hpp_form() {
        let mut ctx = CxxTypeCtx::new(Target::x86_64_apple_darwin());
        let void_ = ctx.intern_type(CxxType::Void);
        let _ = ctx.define_rust_class(ClassDef {
            name: NestedName(vec![
                NameSegment::Namespace(Ident("acme".into())),
                NameSegment::Class(Ident("Widget".into())),
            ]),
            bases: vec![],
            fields: vec![],
            methods: vec![MethodDef { access: Default::default(),
                name: MethodName::Ident(Ident("tick".into())),
                sig: FnSig {
                    params: vec![],
                    ret: void_,
                    cv: CvQual::default(),
                    ref_q: None,
                    variadic: false,
                    noexcept: true,
                },
                virtuality: Virtuality::NonVirtual,
                vtable_index: None,
                special: None,
            }],
            kind: RecordKind::Struct,
            is_polymorphic: false,
            is_final: false,
            source_alignment: None,
        });

        let out = generate_rust_stub_shims(&ctx, "h.hpp").unwrap();
        let ns_open = out.find("namespace acme {").expect("ns open");
        let method = out.find("Widget::tick").expect("method");
        let ns_close = out.find("}  // namespace acme").expect("ns close");
        assert!(ns_open < method);
        assert!(method < ns_close);
    }

    #[test]
    fn cxx_origin_classes_are_ignored() {
        let mut ctx = CxxTypeCtx::new(Target::x86_64_apple_darwin());
        let i32_ = ctx.intern_type(CxxType::Int { signed: true, width: IntWidth::I32 });
        // A C++-origin class; stubs must not reference it.
        let _cxx = ctx.define_class(ClassDef {
            name: NestedName(vec![NameSegment::Class(Ident("Imported".into()))]),
            bases: vec![],
            fields: vec![FieldDef { name: Ident("x".into()), ty: i32_, explicit_align: None }],
            methods: vec![MethodDef { access: Default::default(),
                name: MethodName::Ident(Ident("m".into())),
                sig: FnSig {
                    params: vec![],
                    ret: i32_,
                    cv: CvQual::default(),
                    ref_q: None,
                    variadic: false,
                    noexcept: false,
                },
                virtuality: Virtuality::NonVirtual,
                vtable_index: None,
                special: None,
            }],
            kind: RecordKind::Struct,
            is_polymorphic: false,
            is_final: false,
            source_alignment: None,
        });
        let out = generate_rust_stub_shims(&ctx, "h.hpp").unwrap();
        assert!(
            !out.contains("Imported"),
            "C++-origin class leaked into stubs: {out}"
        );
    }
}
