//! C++ shim generator.
//!
//! Implements the "Rust → C++ direction" of the exception-boundary
//! strategy from `docs/exception_boundary.md §2`: for every method we
//! want to call from Rust, emit an `extern "C" noexcept` trampoline
//! that forwards to the real mangled function and converts any
//! escaping exception into `std::terminate()`.
//!
//! Output is a `.cpp` string the build driver compiles with the user's
//! Clang toolchain and links alongside the rustc-emitted Rust object.
//! The shim symbol name is `__rustcc_shim_<mangled>`, where `<mangled>`
//! is the Itanium symbol produced by `rustc_abi_cxx::mangle()`.
//!
//! Scope for v1:
//! - Non-virtual methods (identifier- or operator-named).
//! - Ctors / dtors / conversion operators: not yet shimmed (they have
//!   lifecycle semantics that pair with `CxxOwned`/`CxxBox` and benefit
//!   from their own entry-point mangling `C1`/`D1`/etc.).
//! - Parameter & return types: scalar builtins, pointer/reference
//!   wrappers, and record types by value. Arrays, function types,
//!   template args in return positions, member pointers: not yet.
//!
//! The generator produces a single `.cpp` file with `#include`s for the
//! user's headers, a standard-library include for `<exception>`, and
//! one shim definition per supported method.

use std::fmt::Write as _;

use rustc_abi_cxx::{
    ClassId, CvQual, CxxType, CxxTypeCtx, FloatKind, IntWidth, MethodDef,
    MethodName, NameSegment, NestedName, OperatorKind, RefKind, SpecialMember,
    Symbol, TemplateArg, TypeId, Virtuality,
};

#[derive(Debug, Clone)]
pub enum ShimError {
    /// A type appeared in a shim signature that the generator can't
    /// render back into C++ source. `where_` is a human-readable
    /// location hint.
    UnsupportedType { where_: String, kind: String },
    /// An operator or conversion-function method name the generator
    /// hasn't implemented.
    UnsupportedMethodName { what: String },
}

impl core::fmt::Display for ShimError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{self:?}")
    }
}

impl std::error::Error for ShimError {}

pub struct ShimOptions<'a> {
    /// Paths (or logical names) to `#include` at the top of the emitted
    /// `.cpp`. These should resolve the class declarations referenced
    /// in the shims.
    pub headers: &'a [&'a str],
    /// The classes to emit shims for. Methods inside each class are
    /// enumerated and shimmed when supported.
    pub classes: &'a [ClassId],
}

pub fn generate_shims(
    ctx: &CxxTypeCtx,
    opts: &ShimOptions<'_>,
) -> Result<String, ShimError> {
    let mut out = String::new();
    out.push_str(
        "// Generated by rustcc cxx_importer::shims. Do not hand-edit.\n\
         // Exception-boundary trampolines per docs/exception_boundary.md.\n\n",
    );
    for header in opts.headers {
        let _ = writeln!(out, "#include \"{header}\"");
    }
    out.push_str("#include <exception>\n\n");

    for &class_id in opts.classes {
        let class = ctx.class(class_id);
        let class_source = render_nested_name(ctx, &class.name)?;

        // M14: heap-allocation thunks. One `__cxx_<class>_new_heap_<i>`
        // per ctor + one `__cxx_<class>_delete`. The bindings emitter
        // pairs these with `pub fn new_boxed(...)` wrappers and
        // `unsafe impl CxxDeletable for <class>` impls so users
        // hold a `CxxHeap<Foo>` instead of a raw pointer.
        //
        // Skip poisoned / opaque classes — we have no
        // constructable / destructable Rust analog for them. Skip
        // also abstract classes: even when their `methods` list
        // includes a public ctor, calling `new AbstractClass(...)`
        // is ill-formed C++ (`error: allocating an object of
        // abstract class type`). A class is abstract iff its
        // vtable still references `__cxa_pure_virtual` after
        // override resolution.
        if !ctx.is_poisoned(class_id) && !is_abstract_class(ctx, class_id) {
            let mut ctor_idx: usize = 0;
            for method in &class.methods {
                let is_ctor = matches!(
                    method.special,
                    Some(SpecialMember::DefaultCtor)
                        | Some(SpecialMember::OtherCtor),
                );
                if !is_ctor {
                    continue;
                }
                let rendered = render_heap_ctor_shim(
                    ctx,
                    &class_source,
                    method,
                    ctor_idx,
                )?;
                out.push_str(&rendered);
                out.push('\n');
                ctor_idx += 1;
            }
            // One delete shim per class — fires C++ `delete` so the
            // matching allocator pair is preserved across the FFI
            // boundary.
            let _ = writeln!(
                out,
                "extern \"C\" void __cxx_{}_delete({class_source}* p) noexcept {{ delete p; }}",
                cxx_class_basename(&class.name),
            );
            out.push('\n');
        }

        for method in &class.methods {
            // Virtuality: virtual methods would need vtable-aware
            // dispatch in the shim; for v1 only non-virtual.
            if method.virtuality != Virtuality::NonVirtual {
                continue;
            }
            // Ctors/dtors/conversion operators have their own entry
            // points (C1/C2/D0/D1/cv<T>) that pair with lifecycle
            // types — skip them here.
            if method.special.is_some() {
                continue;
            }
            if matches!(method.name, MethodName::ConversionTo(_)) {
                continue;
            }
            // Per-method resilience: when shim rendering fails
            // (function-pointer parameter the C++ emitter
            // doesn't have a syntax form for, member-pointer
            // type, etc.), drop just that shim and continue.
            // The Rust bindings emitter has the same
            // skip-with-comment behavior so the resulting
            // surface stays consistent between the Rust
            // declarations and the C++ trampolines.
            match render_method_shim(ctx, class_id, &class_source, method) {
                Ok(rendered) => {
                    out.push_str(&rendered);
                    out.push('\n');
                }
                Err(ShimError::UnsupportedType { where_, kind }) => {
                    let _ = writeln!(
                        out,
                        "// shim skipped: {where_}: {kind}",
                    );
                }
                Err(other) => return Err(other),
            }
        }
    }

    Ok(out)
}

/// Strip the leading namespace path from a `NestedName` and return
/// just the trailing identifier — the basename used as part of the
/// `__cxx_<class>_new_heap_<i>` / `__cxx_<class>_delete` shim
/// symbol. Mirrors what the bindings emitter passes to
/// `format!("__cxx_{class_name}_new_heap_{i}")`.
/// True iff the class has an unoverridden pure-virtual slot in
/// its primary vtable — i.e. C++ would reject `new ClassName(...)`
/// with `error: allocating an object of abstract class type`.
///
/// We use the vtable rather than just walking `class.methods` for
/// `Virtuality::PureVirtual` because a derived class can be
/// abstract through inheritance (e.g. `Mid : Iface {}` where
/// `Iface::do_thing` is pure and Mid doesn't override it). The
/// vtable's slot for that inherited pure virtual still points at
/// `__cxa_pure_virtual` after override resolution, which is the
/// authoritative signal.
fn is_abstract_class(
    ctx: &CxxTypeCtx,
    class_id: ClassId,
) -> bool {
    let vt = match ctx.vtable(class_id) {
        Some(v) => v,
        None => return false,
    };
    for st in &vt.sub_tables {
        for entry in &st.entries {
            if let rustc_abi_cxx::VTableEntry::FunctionPointer {
                mangled_target,
                ..
            } = entry
            {
                if mangled_target == "__cxa_pure_virtual" {
                    return true;
                }
            }
        }
    }
    false
}

fn cxx_class_basename(name: &rustc_abi_cxx::NestedName) -> String {
    use rustc_abi_cxx::NameSegment;
    match name.0.last() {
        Some(NameSegment::Class(i))
        | Some(NameSegment::Namespace(i))
        | Some(NameSegment::Enum(i)) => i.0.clone(),
        Some(NameSegment::TemplateSpec { name, .. }) => name.0.clone(),
        Some(NameSegment::AnonymousNamespace) | None => "<anon>".into(),
    }
}

/// Emit a heap-allocation thunk for one ctor: calls C++ `new
/// <class>(args...)` and returns the raw pointer. The Rust side
/// hands the pointer to `CxxHeap::from_raw` so subsequent drop
/// runs the matching `__cxx_<class>_delete` thunk.
fn render_heap_ctor_shim(
    ctx: &CxxTypeCtx,
    class_source: &str,
    method: &MethodDef,
    ctor_idx: usize,
) -> Result<String, ShimError> {
    let class = match class_source.rsplit("::").next() {
        Some(s) => s.to_string(),
        None => class_source.to_string(),
    };

    let mut params: Vec<String> = Vec::with_capacity(method.sig.params.len());
    let mut args: Vec<String> = Vec::with_capacity(method.sig.params.len());
    for (i, &ty_id) in method.sig.params.iter().enumerate() {
        let ty = render_cxx_type(
            ctx,
            ty_id,
            &format!("{class_source}::ctor[{ctor_idx}] arg {i}"),
        )?;
        params.push(format!("{ty} arg{i}"));
        args.push(format!("arg{i}"));
    }
    let param_list = params.join(", ");
    let arg_list = args.join(", ");

    let mut out = String::new();
    let _ = writeln!(
        out,
        "extern \"C\" {class_source}* __cxx_{class}_new_heap_{ctor_idx}({param_list}) {{",
    );
    let _ = writeln!(
        out,
        "    try {{ return new {class_source}({arg_list}); }} catch (...) {{ std::terminate(); }}",
    );
    let _ = writeln!(out, "}}");
    Ok(out)
}

fn render_method_shim(
    ctx: &CxxTypeCtx,
    class_id: ClassId,
    class_source: &str,
    method: &MethodDef,
) -> Result<String, ShimError> {
    let mangled = ctx.mangle(&Symbol::Method {
        class: class_id,
        name: method.name.clone(),
        sig: method.sig.clone(),
    });
    let shim_sym = format!("__rustcc_shim_{mangled}");

    let ret_src = render_cxx_type(ctx, method.sig.ret, "return type")?;
    let method_call = render_method_callee(&method.name)?;

    // Parameter list. Start with `self` (const-adjusted per the method's
    // cv qualifier). Then method parameters as `argN`.
    let self_const = if method.sig.cv.is_const {
        "const "
    } else {
        ""
    };
    let self_param = format!("{self_const}{class_source}* self");

    let mut params = vec![self_param];
    let mut arg_list = Vec::with_capacity(method.sig.params.len());
    for (i, p) in method.sig.params.iter().enumerate() {
        let ty_src = render_cxx_type(ctx, *p, "parameter")?;
        params.push(format!("{ty_src} arg{i}"));
        arg_list.push(format!("arg{i}"));
    }
    let param_list = params.join(", ");
    let args = arg_list.join(", ");

    let invoke = format!("self->{method_call}({args})");
    let body = if matches!(ctx.type_of(method.sig.ret), CxxType::Void) {
        format!(
            "    try {{\n        {invoke};\n    }} \
             catch (...) {{\n        std::terminate();\n    }}\n"
        )
    } else {
        // C-style cast on the return value bridges the gap
        // between minor cv-qualifier mismatches between our
        // rendered return type and the underlying C++ method's
        // signature. Two cases this papers over:
        //   - Multi-level pointers where the IR's
        //     pointer-vs-pointee cv tracking is approximate
        //     (`Fl_Widget *const *` vs `const Fl_Widget **`).
        //   - Reference-to-pointer return types (`Fl_Widget*&`).
        // The cast is a no-op at runtime when the types are
        // bit-compatible (which is always true for the
        // `extern "C"` ABI surface) and a sharp tool when they
        // aren't — same trade-off C++ users make when
        // round-tripping through `void*`.
        format!(
            "    try {{\n        return ({ret_src})({invoke});\n    }} \
             catch (...) {{\n        std::terminate();\n    }}\n"
        )
    };

    let signature = format!(
        "extern \"C\" {ret_src} {shim_sym}({param_list}) noexcept"
    );
    Ok(format!("{signature} {{\n{body}}}\n"))
}

fn render_method_callee(name: &MethodName) -> Result<String, ShimError> {
    match name {
        MethodName::Ident(i) => Ok(i.0.clone()),
        MethodName::Operator(op) => Ok(format!("{}", operator_source(*op))),
        MethodName::ConversionTo(_) => {
            Err(ShimError::UnsupportedMethodName {
                what: "conversion operator".to_string(),
            })
        }
    }
}

fn operator_source(op: OperatorKind) -> &'static str {
    match op {
        OperatorKind::Plus => "operator+",
        OperatorKind::Minus => "operator-",
        OperatorKind::Mul => "operator*",
        OperatorKind::Div => "operator/",
        OperatorKind::Mod => "operator%",
        OperatorKind::Assign => "operator=",
        OperatorKind::PlusAssign => "operator+=",
        OperatorKind::Eq => "operator==",
        OperatorKind::Ne => "operator!=",
        OperatorKind::Lt => "operator<",
        OperatorKind::Le => "operator<=",
        OperatorKind::Gt => "operator>",
        OperatorKind::Ge => "operator>=",
        OperatorKind::Call => "operator()",
        OperatorKind::Index => "operator[]",
        OperatorKind::Deref => "operator*",
        OperatorKind::PreIncr => "operator++",
        OperatorKind::PreDecr => "operator--",
    }
}

pub(crate) fn render_cxx_type(
    ctx: &CxxTypeCtx,
    ty: TypeId,
    where_: &str,
) -> Result<String, ShimError> {
    let t = ctx.type_of(ty);
    match t {
        CxxType::Void => Ok("void".to_string()),
        CxxType::Bool => Ok("bool".to_string()),
        CxxType::Int { signed, width } => Ok(int_cpp(*signed, *width).to_string()),
        CxxType::Float { kind } => Ok(match kind {
            FloatKind::F32 => "float".to_string(),
            FloatKind::F64 => "double".to_string(),
            FloatKind::LongDouble => "long double".to_string(),
        }),
        CxxType::Ptr { pointee, cv } => {
            let inner = render_cxx_type(ctx, *pointee, where_)?;
            Ok(apply_cv_prefix(&inner, *cv) + "*")
        }
        CxxType::Ref { pointee, kind, cv } => {
            let inner = render_cxx_type(ctx, *pointee, where_)?;
            let sigil = match kind {
                RefKind::Lvalue => "&",
                RefKind::Rvalue => "&&",
            };
            Ok(apply_cv_prefix(&inner, *cv) + sigil)
        }
        CxxType::Record(class_id) => {
            render_nested_name(ctx, &ctx.class(*class_id).name)
        }
        CxxType::Enum { name, .. } => render_nested_name(ctx, name),
        // M15 function-pointer types are deliberately *not*
        // rendered here. The C++ syntax for a function-pointer
        // parameter (`void (*name)(args)`) splices the
        // declarator name *inside* the type, which our
        // single-pass `<type> arg<N>` parameter renderer can't
        // produce. The shim emitter's per-method skip path
        // catches this `UnsupportedType` and emits a
        // `// shim skipped: …` comment so the rest of the
        // class still trampolines cleanly. Proper function-
        // pointer parameter support is tracked as M15.c.
        CxxType::Array { .. }
        | CxxType::Fn(_)
        | CxxType::MemberPtr { .. } => Err(ShimError::UnsupportedType {
            where_: where_.to_string(),
            kind: format!("{t:?}"),
        }),
    }
}

fn int_cpp(signed: bool, width: IntWidth) -> &'static str {
    match (signed, width) {
        // Use plain `char` for the I8-signed case rather than
        // `signed char`. C++ treats `char`, `signed char`, and
        // `unsigned char` as three distinct types — our IR
        // collapses libclang's `CharS`/`SChar` into the same
        // `Int { signed: true, width: I8 }`, so picking either
        // form loses some information. Picking `char` matches
        // the overwhelmingly-common `const char*` string case
        // (FLTK uses it everywhere) and lets the resulting
        // shim source compile cleanly against APIs declared
        // with `char*`. Strict-`signed char*` APIs on the
        // 1% boundary are tracked as a follow-up.
        (true, IntWidth::I8) => "char",
        (false, IntWidth::I8) => "unsigned char",
        (true, IntWidth::I16) => "short",
        (false, IntWidth::I16) => "unsigned short",
        (true, IntWidth::I32) => "int",
        (false, IntWidth::I32) => "unsigned int",
        (true, IntWidth::I64) => "long long",
        (false, IntWidth::I64) => "unsigned long long",
        (true, IntWidth::I128) => "__int128",
        (false, IntWidth::I128) => "unsigned __int128",
    }
}

fn apply_cv_prefix(inner: &str, cv: CvQual) -> String {
    // C++ source form: `const T`, `volatile T`, `const volatile T`.
    // Keep output canonical regardless of argument order. Dedup
    // against an already-prefixed `inner` so multi-level pointer
    // types (`Ptr { pointee: Ptr { pointee: T, cv: const } }`)
    // don't accidentally emit `const const char**`. The IR
    // tracks pointer-vs-pointee cv with some ambiguity around
    // multi-level pointers; the safe rendering rule is to apply
    // each cv qualifier at most once.
    let mut out = String::new();
    if cv.is_const && !inner.starts_with("const ") {
        out.push_str("const ");
    }
    if cv.is_volatile && !inner.starts_with("volatile ") {
        out.push_str("volatile ");
    }
    out.push_str(inner);
    out
}

pub(crate) fn render_nested_name(
    ctx: &CxxTypeCtx,
    name: &NestedName,
) -> Result<String, ShimError> {
    let mut parts = Vec::with_capacity(name.0.len());
    for seg in &name.0 {
        parts.push(render_segment(ctx, seg)?);
    }
    Ok(parts.join("::"))
}

fn render_segment(
    ctx: &CxxTypeCtx,
    seg: &NameSegment,
) -> Result<String, ShimError> {
    match seg {
        NameSegment::Namespace(i)
        | NameSegment::Class(i)
        | NameSegment::Enum(i) => Ok(i.0.clone()),
        NameSegment::AnonymousNamespace => Ok("/* anon */".to_string()),
        NameSegment::TemplateSpec { name, args } => {
            let mut arg_srcs = Vec::with_capacity(args.len());
            for arg in args {
                match arg {
                    TemplateArg::Type(ty) => {
                        arg_srcs.push(render_cxx_type(
                            ctx,
                            *ty,
                            "template argument",
                        )?);
                    }
                    TemplateArg::Integral { value, .. } => {
                        arg_srcs.push(value.to_string());
                    }
                    TemplateArg::Template(nested) => {
                        arg_srcs.push(render_nested_name(ctx, nested)?);
                    }
                }
            }
            Ok(format!("{}<{}>", name.0, arg_srcs.join(", ")))
        }
    }
}
