//! Canonical golden-file format for record layouts.
//!
//! The format is line-oriented so diffs read naturally. Each non-comment,
//! non-blank line is `<key> <value...>`. There is exactly one class per
//! file. `render` and `parse` round-trip.
//!
//! Example:
//!
//! ```text
//! # Generated by `cargo xtask refresh-goldens`. Do not hand-edit.
//! target x86_64-apple-darwin
//! class Foo
//! sizeof 8
//! dsize 8
//! align 4
//! nvsize 8
//! nvalign 4
//! has_vptr false
//! field x 0
//! field y 4
//! ```

use std::fmt::Write as _;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Dump {
    pub target: String,
    pub class: String,
    pub sizeof: u64,
    pub dsize: u64,
    pub align: u64,
    pub nvsize: u64,
    pub nvalign: u64,
    pub has_vptr: bool,
    pub bases: Vec<BaseDump>,
    pub fields: Vec<FieldDump>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BaseDump {
    pub class: String,
    pub offset: u64,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FieldDump {
    pub name: String,
    pub offset: u64,
    /// v1.13.1: bit-field info. `None` for a regular byte-aligned
    /// field; `Some((bit_offset_within_byte, bit_width))` for a
    /// bit-field. Serialized as a `bits <off> <width>` suffix on
    /// the `field` line so existing non-bitfield goldens are
    /// byte-for-byte unchanged.
    pub bits: Option<(u8, u64)>,
}

pub const HEADER: &str =
    "# Generated by `cargo xtask refresh-goldens`. Do not hand-edit.\n";

pub fn render(d: &Dump) -> String {
    let mut out = String::from(HEADER);
    let _ = writeln!(out, "target {}", d.target);
    let _ = writeln!(out, "class {}", d.class);
    let _ = writeln!(out, "sizeof {}", d.sizeof);
    let _ = writeln!(out, "dsize {}", d.dsize);
    let _ = writeln!(out, "align {}", d.align);
    let _ = writeln!(out, "nvsize {}", d.nvsize);
    let _ = writeln!(out, "nvalign {}", d.nvalign);
    let _ = writeln!(out, "has_vptr {}", d.has_vptr);
    for b in &d.bases {
        let _ = writeln!(out, "base {} {}", b.class, b.offset);
    }
    for f in &d.fields {
        match f.bits {
            Some((bit_off, bit_width)) => {
                let _ = writeln!(
                    out,
                    "field {} {} bits {} {}",
                    f.name, f.offset, bit_off, bit_width
                );
            }
            None => {
                let _ = writeln!(out, "field {} {}", f.name, f.offset);
            }
        }
    }
    out
}

pub fn parse(text: &str) -> Result<Dump, String> {
    let mut target = None;
    let mut class = None;
    let mut sizeof = None;
    let mut dsize = None;
    let mut align = None;
    let mut nvsize = None;
    let mut nvalign = None;
    let mut has_vptr = None;
    let mut bases = Vec::new();
    let mut fields = Vec::new();

    for (i, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut toks = line.split_whitespace();
        let key = toks.next().ok_or_else(|| err(i, "empty token"))?;
        match key {
            "target" => target = Some(rest_str(&mut toks).to_string()),
            "class" => class = Some(rest_str(&mut toks).to_string()),
            "sizeof" => sizeof = Some(parse_u64(&mut toks, i, "sizeof")?),
            "dsize" => dsize = Some(parse_u64(&mut toks, i, "dsize")?),
            "align" => align = Some(parse_u64(&mut toks, i, "align")?),
            "nvsize" => nvsize = Some(parse_u64(&mut toks, i, "nvsize")?),
            "nvalign" => nvalign = Some(parse_u64(&mut toks, i, "nvalign")?),
            "has_vptr" => has_vptr = Some(parse_bool(&mut toks, i)?),
            "base" => {
                let name = toks.next().ok_or_else(|| err(i, "missing base name"))?;
                let offset = parse_u64(&mut toks, i, "base offset")?;
                bases.push(BaseDump {
                    class: name.to_string(),
                    offset,
                });
            }
            "field" => {
                let name = toks.next().ok_or_else(|| err(i, "missing field name"))?;
                let offset = parse_u64(&mut toks, i, "field offset")?;
                // Optional `bits <bit_offset> <bit_width>` suffix.
                let bits = match toks.next() {
                    Some("bits") => {
                        let bit_off = parse_u64(&mut toks, i, "bit offset")? as u8;
                        let bit_width = parse_u64(&mut toks, i, "bit width")?;
                        Some((bit_off, bit_width))
                    }
                    Some(other) => {
                        return Err(err(
                            i,
                            &format!("unexpected field token {other:?} (want `bits`)"),
                        ));
                    }
                    None => None,
                };
                fields.push(FieldDump {
                    name: name.to_string(),
                    offset,
                    bits,
                });
            }
            other => return Err(err(i, &format!("unknown key {other:?}"))),
        }
    }

    Ok(Dump {
        target: take(target, "target")?,
        class: take(class, "class")?,
        sizeof: take(sizeof, "sizeof")?,
        dsize: take(dsize, "dsize")?,
        align: take(align, "align")?,
        nvsize: take(nvsize, "nvsize")?,
        nvalign: take(nvalign, "nvalign")?,
        has_vptr: take(has_vptr, "has_vptr")?,
        bases,
        fields,
    })
}

fn rest_str<'a, I>(toks: &mut I) -> String
where
    I: Iterator<Item = &'a str>,
{
    let mut out = String::new();
    for (i, t) in toks.enumerate() {
        if i > 0 {
            out.push(' ');
        }
        out.push_str(t);
    }
    out
}

fn parse_u64<'a, I>(toks: &mut I, line: usize, what: &str) -> Result<u64, String>
where
    I: Iterator<Item = &'a str>,
{
    let s = toks
        .next()
        .ok_or_else(|| err(line, &format!("missing {what}")))?;
    s.parse::<u64>()
        .map_err(|e| err(line, &format!("bad {what} {s:?}: {e}")))
}

fn parse_bool<'a, I>(toks: &mut I, line: usize) -> Result<bool, String>
where
    I: Iterator<Item = &'a str>,
{
    match toks.next() {
        Some("true") => Ok(true),
        Some("false") => Ok(false),
        Some(other) => Err(err(line, &format!("bad bool {other:?}"))),
        None => Err(err(line, "missing bool")),
    }
}

fn take<T>(opt: Option<T>, what: &str) -> Result<T, String> {
    opt.ok_or_else(|| format!("missing {what}"))
}

fn err(line: usize, msg: &str) -> String {
    format!("golden parse error at line {}: {}", line + 1, msg)
}

// -------- Mangling goldens ----------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MangleDump {
    pub target: String,
    pub symbols: Vec<String>,
}

pub fn render_mangle(d: &MangleDump) -> String {
    let mut out = String::from(HEADER);
    let _ = writeln!(out, "target {}", d.target);
    for sym in &d.symbols {
        let _ = writeln!(out, "symbol {sym}");
    }
    out
}

pub fn parse_mangle(text: &str) -> Result<MangleDump, String> {
    let mut target = None;
    let mut symbols = Vec::new();
    for (i, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut toks = line.split_whitespace();
        let key = toks.next().ok_or_else(|| err(i, "empty token"))?;
        match key {
            "target" => target = Some(rest_str(&mut toks)),
            "symbol" => {
                let sym = toks
                    .next()
                    .ok_or_else(|| err(i, "missing symbol"))?
                    .to_string();
                symbols.push(sym);
            }
            other => return Err(err(i, &format!("unknown key {other:?}"))),
        }
    }
    Ok(MangleDump {
        target: take(target, "target")?,
        symbols,
    })
}

// -------- Vtable goldens ------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VtableDump {
    pub target: String,
    pub class: String,
    pub sub_tables: Vec<VtableSubTableDump>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VtableSubTableDump {
    /// `for_subobject` in the class path form, e.g. "PA" or "PB".
    /// "primary" is a convenience alias used when the subobject is the
    /// most-derived class itself.
    pub for_subobject: String,
    pub subobject_offset: u64,
    /// Slot index, measured from this sub-table's start (not from
    /// `_ZTV<class>`'s start). Typically 2, i.e. just past
    /// `offset_to_top` and the RTTI pointer.
    pub address_point_slot: u64,
    pub entries: Vec<VtableEntryDump>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum VtableEntryDump {
    VbaseOffset(i64),
    OffsetToTop(i64),
    Rtti(String),
    FunctionPointer(String),
}

pub fn render_vtable(d: &VtableDump) -> String {
    let mut out = String::from(HEADER);
    let _ = writeln!(out, "target {}", d.target);
    let _ = writeln!(out, "class {}", d.class);
    for sub in &d.sub_tables {
        let _ = writeln!(
            out,
            "subtable for={} offset={} address_point_slot={}",
            sub.for_subobject, sub.subobject_offset, sub.address_point_slot
        );
        for (i, entry) in sub.entries.iter().enumerate() {
            match entry {
                VtableEntryDump::VbaseOffset(v) => {
                    let _ = writeln!(out, "  entry {i} vbase_offset {v}");
                }
                VtableEntryDump::OffsetToTop(v) => {
                    let _ = writeln!(out, "  entry {i} offset_to_top {v}");
                }
                VtableEntryDump::Rtti(s) => {
                    let _ = writeln!(out, "  entry {i} rtti {s}");
                }
                VtableEntryDump::FunctionPointer(s) => {
                    let _ = writeln!(out, "  entry {i} fn {s}");
                }
            }
        }
    }
    out
}

pub fn parse_vtable(text: &str) -> Result<VtableDump, String> {
    let mut target = None;
    let mut class = None;
    let mut sub_tables: Vec<VtableSubTableDump> = Vec::new();
    for (i, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut toks = line.split_whitespace();
        let key = toks.next().ok_or_else(|| err(i, "empty token"))?;
        match key {
            "target" => target = Some(rest_str(&mut toks)),
            "class" => class = Some(rest_str(&mut toks)),
            "subtable" => {
                // `subtable for=<name> offset=<n> address_point_slot=<n>`
                let mut for_ = None;
                let mut offset = None;
                let mut ap_slot = None;
                for tok in toks {
                    if let Some(v) = tok.strip_prefix("for=") {
                        for_ = Some(v.to_string());
                    } else if let Some(v) = tok.strip_prefix("offset=") {
                        offset = Some(v.parse::<u64>().map_err(|e| {
                            err(i, &format!("bad offset: {e}"))
                        })?);
                    } else if let Some(v) =
                        tok.strip_prefix("address_point_slot=")
                    {
                        ap_slot = Some(v.parse::<u64>().map_err(|e| {
                            err(i, &format!("bad slot: {e}"))
                        })?);
                    }
                }
                sub_tables.push(VtableSubTableDump {
                    for_subobject: take(for_, "subtable for=")?,
                    subobject_offset: take(offset, "subtable offset=")?,
                    address_point_slot: take(
                        ap_slot,
                        "subtable address_point_slot=",
                    )?,
                    entries: Vec::new(),
                });
            }
            "entry" => {
                let sub = sub_tables.last_mut().ok_or_else(|| {
                    err(i, "`entry` before any `subtable` line")
                })?;
                let idx = parse_u64(&mut toks, i, "entry index")? as usize;
                let kind = toks
                    .next()
                    .ok_or_else(|| err(i, "missing entry kind"))?;
                let entry = match kind {
                    "vbase_offset" => {
                        let v = toks
                            .next()
                            .ok_or_else(|| err(i, "missing vbase offset"))?;
                        let v: i64 = v.parse().map_err(|e| {
                            err(i, &format!("bad vbase_offset: {e}"))
                        })?;
                        VtableEntryDump::VbaseOffset(v)
                    }
                    "offset_to_top" => {
                        let v = toks
                            .next()
                            .ok_or_else(|| err(i, "missing offset"))?;
                        let v: i64 = v
                            .parse()
                            .map_err(|e| err(i, &format!("bad offset: {e}")))?;
                        VtableEntryDump::OffsetToTop(v)
                    }
                    "rtti" => VtableEntryDump::Rtti(
                        toks.next()
                            .ok_or_else(|| err(i, "missing rtti symbol"))?
                            .to_string(),
                    ),
                    "fn" => VtableEntryDump::FunctionPointer(
                        toks.next()
                            .ok_or_else(|| err(i, "missing fn symbol"))?
                            .to_string(),
                    ),
                    other => {
                        return Err(err(
                            i,
                            &format!("unknown entry kind {other:?}"),
                        ))
                    }
                };
                if sub.entries.len() <= idx {
                    sub.entries
                        .resize(idx + 1, VtableEntryDump::OffsetToTop(0));
                }
                sub.entries[idx] = entry;
            }
            other => return Err(err(i, &format!("unknown key {other:?}"))),
        }
    }
    Ok(VtableDump {
        target: take(target, "target")?,
        class: take(class, "class")?,
        sub_tables,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Dump {
        Dump {
            target: "x86_64-apple-darwin".into(),
            class: "Foo".into(),
            sizeof: 8,
            dsize: 8,
            align: 4,
            nvsize: 8,
            nvalign: 4,
            has_vptr: false,
            bases: Vec::new(),
            fields: vec![
                FieldDump {
                    name: "x".into(),
                    offset: 0,
                    bits: None,
                },
                FieldDump {
                    name: "y".into(),
                    offset: 4,
                    bits: None,
                },
            ],
        }
    }

    #[test]
    fn round_trips() {
        let text = render(&sample());
        let parsed = parse(&text).expect("parse");
        assert_eq!(parsed, sample());
    }

    #[test]
    fn bitfield_dump_round_trips() {
        // v1.13.1: a Dump carrying bit-field fields must survive
        // render → parse unchanged, and the serialized form must
        // use the `bits <off> <width>` suffix.
        let d = Dump {
            target: "x86_64-apple-darwin".into(),
            class: "BF".into(),
            sizeof: 8,
            dsize: 8,
            align: 4,
            nvsize: 8,
            nvalign: 4,
            has_vptr: false,
            bases: Vec::new(),
            fields: vec![
                FieldDump { name: "a".into(), offset: 0, bits: Some((0, 4)) },
                FieldDump { name: "b".into(), offset: 0, bits: Some((4, 20)) },
                FieldDump { name: "tail".into(), offset: 4, bits: None },
            ],
        };
        let text = render(&d);
        assert!(text.contains("field a 0 bits 0 4"), "serialized form:\n{text}");
        assert!(text.contains("field tail 4\n"), "plain field unchanged:\n{text}");
        let parsed = parse(&text).expect("parse");
        assert_eq!(parsed, d);
    }

    #[test]
    fn ignores_blank_and_comment_lines() {
        let mut text = render(&sample());
        text.insert_str(0, "\n# extra comment\n\n");
        let parsed = parse(&text).expect("parse");
        assert_eq!(parsed, sample());
    }

    #[test]
    fn reports_missing_field() {
        let text = "class Foo\nsizeof 8\n";
        let err = parse(text).unwrap_err();
        assert!(err.contains("missing"));
    }

    fn mangle_sample() -> MangleDump {
        MangleDump {
            target: "x86_64-apple-darwin".into(),
            symbols: vec![
                "_Z7free_fni".into(),
                "_ZN3FooC1Ev".into(),
                "_ZN3FooD1Ev".into(),
                "_ZNK3Foo3barEd".into(),
            ],
        }
    }

    #[test]
    fn mangle_round_trips() {
        let text = render_mangle(&mangle_sample());
        let parsed = parse_mangle(&text).expect("parse");
        assert_eq!(parsed, mangle_sample());
    }

    fn vtable_sample() -> VtableDump {
        VtableDump {
            target: "x86_64-apple-darwin".into(),
            class: "Base".into(),
            sub_tables: vec![VtableSubTableDump {
                for_subobject: "Base".into(),
                subobject_offset: 0,
                address_point_slot: 2,
                entries: vec![
                    VtableEntryDump::OffsetToTop(0),
                    VtableEntryDump::Rtti("_ZTI4Base".into()),
                    VtableEntryDump::FunctionPointer("_ZN4BaseD1Ev".into()),
                    VtableEntryDump::FunctionPointer("_ZN4BaseD0Ev".into()),
                    VtableEntryDump::FunctionPointer(
                        "_ZN4Base6renderEv".into(),
                    ),
                ],
            }],
        }
    }

    #[test]
    fn vtable_round_trips() {
        let text = render_vtable(&vtable_sample());
        let parsed = parse_vtable(&text).expect("parse");
        assert_eq!(parsed, vtable_sample());
    }
}
