//! v1.12.21 cxx_throws end-to-end demo.
//!
//! Exercises every flavor of the throws system:
//!   - non-throwing free fn (control)
//!   - catch-all free fn → CxxException::is_std() / what()
//!   - typed-catches free fn → CxxException::is_typed_at(idx)
//!   - throwing constructor → Result<Self, _>
//!   - throwing class method → Result<T, _>
//!
//! Build + run with:
//!   cargo run -p cxx_throws_demo
//!
//! Stock rustc — no fork required. The throws path uses
//! `extern "C"` shims (NOT `extern "C++"`), so the bindings
//! compile cleanly on the default toolchain.

// The `bindings.rs` generated by cxx_importer's build orchestrator
// reaches the `Result` decode helpers via `::cxx::CxxException`
// etc., so we depend on the `cxx` runtime crate.
use cxx::CxxException;

// Pull the generated bindings — Result wrappers for every
// throws-annotated function in cpp/library.hpp, plus a plain
// wrapper for `add` (the non-annotated control).
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

fn main() {
    // 1. `add` is annotated as cxx_throws so this demo
    //    compiles on stock rustc (see library.hpp comments).
    //    The function never throws in practice — every call
    //    returns Ok(_).
    print_result("add(2, 3)", add(2, 3));

    // 2. Catch-all throws: do_divide(10, 0) raises
    //    std::runtime_error("divide by zero") on the C++ side.
    //    The shim's std::exception arm catches it; we get
    //    `Err(CxxException { kind: Std, message: "divide by zero" })`.
    print_result("do_divide(10, 2)", do_divide(10, 2));
    print_result("do_divide(10, 0)", do_divide(10, 0));

    // 3. Typed catches: compute() throws different types per
    //    selector. We dispatch via is_typed_at(idx).
    for selector in 0..=4 {
        match compute(selector) {
            Ok(v) => println!("compute({selector}) = Ok({v})"),
            Err(ref e) if e.is_typed_at(0) => {
                println!("compute({selector}) = DomainError({})", e.what());
            }
            Err(ref e) if e.is_typed_at(1) => {
                println!("compute({selector}) = RangeError({})", e.what());
            }
            Err(ref e) if e.is_std() => {
                println!("compute({selector}) = Std({})", e.what());
            }
            Err(ref e) => {
                println!("compute({selector}) = Unknown({})", e.what());
            }
        }
    }

    // 4. Throwing constructor: Calc::new(-1) raises DomainError.
    match Calc::new(42) {
        Ok(mut c) => {
            print_result_int("c.read()", c.read());
            // 5. Throwing class method: divide(0) on a real Calc.
            print_result_int("c.divide(7)", c.divide(7));
            print_result_int("c.divide(0)", c.divide(0));
        }
        Err(e) => println!("Calc::new(42) UNEXPECTED ERROR: {e}"),
    }
    match Calc::new(-1) {
        Ok(c) => {
            let _ = c;
            println!("Calc::new(-1) UNEXPECTED OK");
        }
        Err(e) => println!("Calc::new(-1) = Err({})", e.what()),
    }
}

fn print_result(label: &str, r: Result<i32, CxxException>) {
    match r {
        Ok(v) => println!("{label} = Ok({v})"),
        Err(e) => println!("{label} = Err({e})"),
    }
}

fn print_result_int(label: &str, r: Result<i32, CxxException>) {
    print_result(label, r);
}
