//! MSVC mangling corpus — golden symbols generated by
//! `clang -target x86_64-pc-windows-msvc -fms-compatibility` against
//! the .cpp sources in `tests/corpus_msvc/`, plus per-symbol diff tests
//! that exercise `ctx.mangle_msvc()` against the same goldens.
//!
//! The goldens are checked in (not regenerated at test time) so the
//! suite runs without a network or a working cross-target clang. To
//! refresh after editing the .cpp files, run
//! `fork/tests/refresh-msvc-corpus.sh` from the rustcc tree.

use std::collections::HashSet;
use std::path::PathBuf;

use rustc_abi_cxx::{
    Access, BaseSpec, ClassDef, ClassId, CtorVariant, CvQual, CxxType,
    CxxTypeCtx, DtorVariant, FloatKind, FnSig, Ident, IntWidth, MethodName,
    NameSegment, NestedName, OperatorKind, RecordKind, RefKind, Symbol,
    TemplateArg, Target, TypeId, Virtuality,
};
use test_support::golden::{self, MangleDump};

fn corpus_path(filename: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/corpus_msvc")
        .join(filename)
}

fn load(basename: &str) -> MangleDump {
    let path = corpus_path(&format!("{basename}.mangle.golden"));
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "failed to read {} ({e}). Run \
             fork/tests/refresh-msvc-corpus.sh.",
            path.display()
        )
    });
    golden::parse_mangle(&text).unwrap_or_else(|e| {
        panic!("failed to parse {}: {e}", path.display())
    })
}

fn ctx() -> CxxTypeCtx {
    CxxTypeCtx::new(Target::x86_64_pc_windows_msvc())
}

fn intern_int(ctx: &mut CxxTypeCtx, signed: bool, width: IntWidth) -> TypeId {
    ctx.intern_type(CxxType::Int { signed, width })
}

fn intern_void(ctx: &mut CxxTypeCtx) -> TypeId {
    ctx.intern_type(CxxType::Void)
}

fn intern_float(ctx: &mut CxxTypeCtx, kind: FloatKind) -> TypeId {
    ctx.intern_type(CxxType::Float { kind })
}

fn assert_all_msvc(dump: &MangleDump, expected: &[(&str, &str)]) {
    let set: HashSet<&str> = dump.symbols.iter().map(String::as_str).collect();
    let missing: Vec<_> = expected
        .iter()
        .filter(|(_, m)| !set.contains(*m))
        .collect();
    assert!(
        missing.is_empty(),
        "expected MSVC symbols missing from golden — clang's output may \
         have changed, or the .cpp no longer defines them: {missing:?}"
    );
}

// -------- mangle_basic --------------------------------------------------

const BASIC_EXPECTED: &[(&str, &str)] = &[
    ("Foo::Foo()", "??0Foo@@QEAA@XZ"),
    ("Foo::Foo(int)", "??0Foo@@QEAA@H@Z"),
    ("Foo::~Foo()", "??1Foo@@QEAA@XZ"),
    ("Foo::bar(int)", "?bar@Foo@@QEAAXH@Z"),
    ("Foo::bar(double) const", "?bar@Foo@@QEBAXN@Z"),
    ("free_fn(int)", "?free_fn@@YAXH@Z"),
];

#[test]
fn msvc_basic_golden_has_expected_symbols() {
    let d = load("mangle_basic");
    assert_all_msvc(&d, BASIC_EXPECTED);
    for s in &d.symbols {
        assert!(
            s.starts_with('?'),
            "MSVC mangled symbol should start with '?': {s}"
        );
    }
}

#[test]
fn msvc_basic_matches_clang() {
    let mut c = ctx();
    let i = intern_int(&mut c, true, IntWidth::I32);
    let v = intern_void(&mut c);
    let d = intern_float(&mut c, FloatKind::F64);
    let foo = c.define_class(ClassDef {
        name: NestedName(vec![NameSegment::Class(Ident("Foo".into()))]),
        bases: vec![],
        fields: vec![],
        methods: vec![],
        kind: RecordKind::Struct,
        is_polymorphic: false,
        is_final: false,
        source_alignment: None,
    });

    // free_fn(int)
    let sig = FnSig {
        params: vec![i],
        ret: v,
        cv: CvQual::default(),
        ref_q: None,
        variadic: false,
        noexcept: false,
    };
    assert_eq!(
        c.mangle_msvc(&Symbol::Function {
            scope: NestedName(vec![]),
            name: Ident("free_fn".into()),
            sig: sig.clone(),
        }),
        "?free_fn@@YAXH@Z"
    );

    // Foo::Foo()
    let ctor_sig0 = FnSig {
        params: vec![],
        ret: v,
        cv: CvQual::default(),
        ref_q: None,
        variadic: false,
        noexcept: false,
    };
    assert_eq!(
        c.mangle_msvc(&Symbol::Ctor {
            class: foo,
            variant: CtorVariant::C1,
            sig: ctor_sig0,
        }),
        "??0Foo@@QEAA@XZ"
    );

    // Foo::Foo(int)
    let ctor_sig1 = FnSig {
        params: vec![i],
        ret: v,
        cv: CvQual::default(),
        ref_q: None,
        variadic: false,
        noexcept: false,
    };
    assert_eq!(
        c.mangle_msvc(&Symbol::Ctor {
            class: foo,
            variant: CtorVariant::C1,
            sig: ctor_sig1,
        }),
        "??0Foo@@QEAA@H@Z"
    );

    // Foo::~Foo()
    assert_eq!(
        c.mangle_msvc(&Symbol::Dtor {
            class: foo,
            variant: DtorVariant::D1,
        }),
        "??1Foo@@QEAA@XZ"
    );

    // Foo::bar(int)
    let bar_int_sig = FnSig {
        params: vec![i],
        ret: v,
        cv: CvQual::default(),
        ref_q: None,
        variadic: false,
        noexcept: false,
    };
    assert_eq!(
        c.mangle_msvc(&Symbol::Method {
            class: foo,
            name: MethodName::Ident(Ident("bar".into())),
            sig: bar_int_sig,
        }),
        "?bar@Foo@@QEAAXH@Z"
    );

    // Foo::bar(double) const
    let bar_d_sig = FnSig {
        params: vec![d],
        ret: v,
        cv: CvQual { is_const: true, is_volatile: false },
        ref_q: None,
        variadic: false,
        noexcept: false,
    };
    assert_eq!(
        c.mangle_msvc(&Symbol::Method {
            class: foo,
            name: MethodName::Ident(Ident("bar".into())),
            sig: bar_d_sig,
        }),
        "?bar@Foo@@QEBAXN@Z"
    );
}

// -------- mangle_types --------------------------------------------------

const TYPES_EXPECTED: &[(&str, &str)] = &[
    ("void", "?t_void@@YAXXZ"),
    ("bool", "?t_bool@@YAX_N@Z"),
    ("char", "?t_int8@@YAXD@Z"),
    ("unsigned char", "?t_uint8@@YAXE@Z"),
    ("short", "?t_int16@@YAXF@Z"),
    ("unsigned short", "?t_uint16@@YAXG@Z"),
    ("int", "?t_int32@@YAXH@Z"),
    ("unsigned int", "?t_uint32@@YAXI@Z"),
    ("long long", "?t_int64@@YAX_J@Z"),
    ("unsigned long long", "?t_uint64@@YAX_K@Z"),
    ("float", "?t_f32@@YAXM@Z"),
    ("double", "?t_f64@@YAXN@Z"),
    ("int*", "?p_int@@YAXPEAH@Z"),
    ("const int*", "?p_const_int@@YAXPEBH@Z"),
    ("volatile int*", "?p_volatile_int@@YAXPECH@Z"),
    ("const volatile int*", "?p_const_volatile_int@@YAXPEDH@Z"),
    ("int**", "?p_p_int@@YAXPEAPEAH@Z"),
    ("int&", "?r_int@@YAXAEAH@Z"),
    ("const int&", "?r_const_int@@YAXAEBH@Z"),
];

#[test]
fn msvc_types_golden_has_expected_symbols() {
    let d = load("mangle_types");
    assert_all_msvc(&d, TYPES_EXPECTED);
}

#[test]
fn msvc_types_matches_clang() {
    let mut c = ctx();
    let v = intern_void(&mut c);

    fn free_void_taking(
        c: &mut CxxTypeCtx,
        name: &str,
        param: TypeId,
        ret: TypeId,
    ) -> String {
        let sig = FnSig {
            params: vec![param],
            ret,
            cv: CvQual::default(),
            ref_q: None,
            variadic: false,
            noexcept: false,
        };
        c.mangle_msvc(&Symbol::Function {
            scope: NestedName(vec![]),
            name: Ident(name.into()),
            sig,
        })
    }

    // Builtin types
    let cases = [
        ("t_bool", CxxType::Bool, "?t_bool@@YAX_N@Z"),
        (
            "t_int8",
            CxxType::Int { signed: true, width: IntWidth::I8 },
            "?t_int8@@YAXD@Z",
        ),
        (
            "t_uint8",
            CxxType::Int { signed: false, width: IntWidth::I8 },
            "?t_uint8@@YAXE@Z",
        ),
        (
            "t_int16",
            CxxType::Int { signed: true, width: IntWidth::I16 },
            "?t_int16@@YAXF@Z",
        ),
        (
            "t_uint16",
            CxxType::Int { signed: false, width: IntWidth::I16 },
            "?t_uint16@@YAXG@Z",
        ),
        (
            "t_int32",
            CxxType::Int { signed: true, width: IntWidth::I32 },
            "?t_int32@@YAXH@Z",
        ),
        (
            "t_uint32",
            CxxType::Int { signed: false, width: IntWidth::I32 },
            "?t_uint32@@YAXI@Z",
        ),
        (
            "t_int64",
            CxxType::Int { signed: true, width: IntWidth::I64 },
            "?t_int64@@YAX_J@Z",
        ),
        (
            "t_uint64",
            CxxType::Int { signed: false, width: IntWidth::I64 },
            "?t_uint64@@YAX_K@Z",
        ),
        (
            "t_f32",
            CxxType::Float { kind: FloatKind::F32 },
            "?t_f32@@YAXM@Z",
        ),
        (
            "t_f64",
            CxxType::Float { kind: FloatKind::F64 },
            "?t_f64@@YAXN@Z",
        ),
    ];
    for (name, ty, expected) in cases {
        let id = c.intern_type(ty);
        let got = free_void_taking(&mut c, name, id, v);
        assert_eq!(
            got, expected,
            "mangling of {name}: got {got}, expected {expected}"
        );
    }

    // t_void() - special case (no params)
    let void_sig = FnSig {
        params: vec![],
        ret: v,
        cv: CvQual::default(),
        ref_q: None,
        variadic: false,
        noexcept: false,
    };
    assert_eq!(
        c.mangle_msvc(&Symbol::Function {
            scope: NestedName(vec![]),
            name: Ident("t_void".into()),
            sig: void_sig,
        }),
        "?t_void@@YAXXZ"
    );

    // Pointer variants
    let i = intern_int(&mut c, true, IntWidth::I32);
    let p = c.intern_type(CxxType::Ptr { pointee: i, cv: CvQual::default() });
    let pc = c.intern_type(CxxType::Ptr {
        pointee: i,
        cv: CvQual { is_const: true, is_volatile: false },
    });
    let pv = c.intern_type(CxxType::Ptr {
        pointee: i,
        cv: CvQual { is_const: false, is_volatile: true },
    });
    let pcv = c.intern_type(CxxType::Ptr {
        pointee: i,
        cv: CvQual { is_const: true, is_volatile: true },
    });
    let pp = c.intern_type(CxxType::Ptr { pointee: p, cv: CvQual::default() });
    let r = c.intern_type(CxxType::Ref {
        pointee: i,
        kind: RefKind::Lvalue,
        cv: CvQual::default(),
    });
    let rc = c.intern_type(CxxType::Ref {
        pointee: i,
        kind: RefKind::Lvalue,
        cv: CvQual { is_const: true, is_volatile: false },
    });

    let ptr_cases = [
        ("p_int", p, "?p_int@@YAXPEAH@Z"),
        ("p_const_int", pc, "?p_const_int@@YAXPEBH@Z"),
        ("p_volatile_int", pv, "?p_volatile_int@@YAXPECH@Z"),
        ("p_const_volatile_int", pcv, "?p_const_volatile_int@@YAXPEDH@Z"),
        ("p_p_int", pp, "?p_p_int@@YAXPEAPEAH@Z"),
        ("r_int", r, "?r_int@@YAXAEAH@Z"),
        ("r_const_int", rc, "?r_const_int@@YAXAEBH@Z"),
    ];
    for (name, ty, expected) in ptr_cases {
        let got = free_void_taking(&mut c, name, ty, v);
        assert_eq!(
            got, expected,
            "mangling of {name}: got {got}, expected {expected}"
        );
    }
}

// -------- mangle_nested ------------------------------------------------

const NESTED_EXPECTED: &[(&str, &str)] = &[
    ("N::M::f(N::M::S)", "?f@M@N@@YAHUS@12@@Z"),
    ("N::g(N::M::S)", "?g@N@@YAHUS@M@1@@Z"),
];

#[test]
fn msvc_nested_golden_has_expected_symbols() {
    let d = load("mangle_nested");
    assert_all_msvc(&d, NESTED_EXPECTED);
}

#[test]
fn msvc_nested_matches_clang() {
    let mut c = ctx();
    let i = intern_int(&mut c, true, IntWidth::I32);
    // namespace N { namespace M { struct S { int x; }; ... } }
    let s = c.define_class(ClassDef {
        name: NestedName(vec![
            NameSegment::Namespace(Ident("N".into())),
            NameSegment::Namespace(Ident("M".into())),
            NameSegment::Class(Ident("S".into())),
        ]),
        bases: vec![],
        fields: vec![],
        methods: vec![],
        kind: RecordKind::Struct,
        is_polymorphic: false,
        is_final: false,
        source_alignment: None,
    });
    let s_ty = c.intern_type(CxxType::Record(s));

    // N::M::f(N::M::S) -> ?f@M@N@@YAHUS@12@@Z
    let f_sig = FnSig {
        params: vec![s_ty],
        ret: i,
        cv: CvQual::default(),
        ref_q: None,
        variadic: false,
        noexcept: false,
    };
    let f_mangled = c.mangle_msvc(&Symbol::Function {
        scope: NestedName(vec![
            NameSegment::Namespace(Ident("N".into())),
            NameSegment::Namespace(Ident("M".into())),
        ]),
        name: Ident("f".into()),
        sig: f_sig,
    });
    assert_eq!(f_mangled, "?f@M@N@@YAHUS@12@@Z");

    // N::g(N::M::S) -> ?g@N@@YAHUS@M@1@@Z
    let mut c2 = ctx();
    let i2 = intern_int(&mut c2, true, IntWidth::I32);
    let s2 = c2.define_class(ClassDef {
        name: NestedName(vec![
            NameSegment::Namespace(Ident("N".into())),
            NameSegment::Namespace(Ident("M".into())),
            NameSegment::Class(Ident("S".into())),
        ]),
        bases: vec![],
        fields: vec![],
        methods: vec![],
        kind: RecordKind::Struct,
        is_polymorphic: false,
        is_final: false,
        source_alignment: None,
    });
    let s2_ty = c2.intern_type(CxxType::Record(s2));
    let g_sig = FnSig {
        params: vec![s2_ty],
        ret: i2,
        cv: CvQual::default(),
        ref_q: None,
        variadic: false,
        noexcept: false,
    };
    let g_mangled = c2.mangle_msvc(&Symbol::Function {
        scope: NestedName(vec![NameSegment::Namespace(Ident("N".into()))]),
        name: Ident("g".into()),
        sig: g_sig,
    });
    assert_eq!(g_mangled, "?g@N@@YAHUS@M@1@@Z");
}

// -------- mangle_operators ---------------------------------------------

const OPERATORS_EXPECTED: &[(&str, &str)] = &[
    // ??4 = operator=. Returns Vec& (lvalue ref), takes const Vec&.
    ("Vec::operator=", "??4Vec@@QEAAAEAU0@AEBU0@@Z"),
    // ??8 = operator== const. Returns bool, takes const Vec&.
    ("Vec::operator==", "??8Vec@@QEBA_NAEBU0@@Z"),
    // ??A = operator[]. Returns int, takes int.
    ("Vec::operator[]", "??AVec@@QEAAHH@Z"),
    // ??H = operator+ const. Returns Vec by value (?A prefix),
    // takes const Vec&.
    ("Vec::operator+", "??HVec@@QEBA?AU0@AEBU0@@Z"),
    // ??M = operator< const. Returns bool, takes const Vec&.
    ("Vec::operator<", "??MVec@@QEBA_NAEBU0@@Z"),
];

#[test]
fn msvc_operators_golden_has_expected_symbols() {
    let d = load("mangle_operators");
    assert_all_msvc(&d, OPERATORS_EXPECTED);
}

#[test]
fn msvc_operators_matches_clang() {
    let mut c = ctx();
    let i = intern_int(&mut c, true, IntWidth::I32);
    let b = c.intern_type(CxxType::Bool);
    let vec = c.define_class(ClassDef {
        name: NestedName(vec![NameSegment::Class(Ident("Vec".into()))]),
        bases: vec![],
        fields: vec![],
        methods: vec![],
        kind: RecordKind::Struct,
        is_polymorphic: false,
        is_final: false,
        source_alignment: None,
    });
    let vec_ty = c.intern_type(CxxType::Record(vec));
    let vec_ref = c.intern_type(CxxType::Ref {
        pointee: vec_ty,
        kind: RefKind::Lvalue,
        cv: CvQual::default(),
    });
    let vec_cref = c.intern_type(CxxType::Ref {
        pointee: vec_ty,
        kind: RefKind::Lvalue,
        cv: CvQual { is_const: true, is_volatile: false },
    });

    // Vec::operator+(const Vec&) const -> ??HVec@@QEBA?AU0@AEBU0@@Z
    let plus_sig = FnSig {
        params: vec![vec_cref],
        ret: vec_ty,
        cv: CvQual { is_const: true, is_volatile: false },
        ref_q: None,
        variadic: false,
        noexcept: false,
    };
    assert_eq!(
        c.mangle_msvc(&Symbol::Method {
            class: vec,
            name: MethodName::Operator(OperatorKind::Plus),
            sig: plus_sig,
        }),
        "??HVec@@QEBA?AU0@AEBU0@@Z"
    );

    // Vec::operator=(const Vec&) -> ??4Vec@@QEAAAEAU0@AEBU0@@Z
    let assign_sig = FnSig {
        params: vec![vec_cref],
        ret: vec_ref,
        cv: CvQual::default(),
        ref_q: None,
        variadic: false,
        noexcept: false,
    };
    assert_eq!(
        c.mangle_msvc(&Symbol::Method {
            class: vec,
            name: MethodName::Operator(OperatorKind::Assign),
            sig: assign_sig,
        }),
        "??4Vec@@QEAAAEAU0@AEBU0@@Z"
    );

    // Vec::operator[](int) -> ??AVec@@QEAAHH@Z
    let index_sig = FnSig {
        params: vec![i],
        ret: i,
        cv: CvQual::default(),
        ref_q: None,
        variadic: false,
        noexcept: false,
    };
    assert_eq!(
        c.mangle_msvc(&Symbol::Method {
            class: vec,
            name: MethodName::Operator(OperatorKind::Index),
            sig: index_sig,
        }),
        "??AVec@@QEAAHH@Z"
    );

    // Vec::operator==(const Vec&) const -> ??8Vec@@QEBA_NAEBU0@@Z
    let eq_sig = FnSig {
        params: vec![vec_cref],
        ret: b,
        cv: CvQual { is_const: true, is_volatile: false },
        ref_q: None,
        variadic: false,
        noexcept: false,
    };
    assert_eq!(
        c.mangle_msvc(&Symbol::Method {
            class: vec,
            name: MethodName::Operator(OperatorKind::Eq),
            sig: eq_sig,
        }),
        "??8Vec@@QEBA_NAEBU0@@Z"
    );

    // Vec::operator<(const Vec&) const -> ??MVec@@QEBA_NAEBU0@@Z
    let lt_sig = FnSig {
        params: vec![vec_cref],
        ret: b,
        cv: CvQual { is_const: true, is_volatile: false },
        ref_q: None,
        variadic: false,
        noexcept: false,
    };
    assert_eq!(
        c.mangle_msvc(&Symbol::Method {
            class: vec,
            name: MethodName::Operator(OperatorKind::Lt),
            sig: lt_sig,
        }),
        "??MVec@@QEBA_NAEBU0@@Z"
    );
}

// -------- mangle_inherit (virtual methods) -----------------------------

const INHERIT_EXPECTED: &[(&str, &str)] = &[
    ("Base::f(int) [virtual]", "?f@Base@@UEAAXH@Z"),
    ("Base::g() const [virtual]", "?g@Base@@UEBAHXZ"),
    ("Base::~Base() [virtual]", "??1Base@@UEAA@XZ"),
    ("Derived::f(int) [override]", "?f@Derived@@UEAAXH@Z"),
    ("Derived::g() const [override]", "?g@Derived@@UEBAHXZ"),
    ("Derived::~Derived() [virtual]", "??1Derived@@UEAA@XZ"),
];

#[test]
fn msvc_inherit_golden_has_expected_symbols() {
    let d = load("mangle_inherit");
    assert_all_msvc(&d, INHERIT_EXPECTED);
}

#[test]
fn msvc_inherit_matches_clang_virtual_access_letter() {
    let mut c = ctx();
    let v = intern_void(&mut c);
    let i = intern_int(&mut c, true, IntWidth::I32);

    // struct Base { virtual void f(int); virtual int g() const; virtual ~Base(); };
    let f_method = rustc_abi_cxx::MethodDef {
        name: MethodName::Ident(Ident("f".into())),
        sig: FnSig {
            params: vec![i],
            ret: v,
            cv: CvQual::default(),
            ref_q: None,
            variadic: false,
            noexcept: false,
        },
        virtuality: Virtuality::Virtual,
        vtable_index: None,
        special: None,
    };
    let g_method = rustc_abi_cxx::MethodDef {
        name: MethodName::Ident(Ident("g".into())),
        sig: FnSig {
            params: vec![],
            ret: i,
            cv: CvQual { is_const: true, is_volatile: false },
            ref_q: None,
            variadic: false,
            noexcept: false,
        },
        virtuality: Virtuality::Virtual,
        vtable_index: None,
        special: None,
    };
    let dtor_method = rustc_abi_cxx::MethodDef {
        name: MethodName::Ident(Ident("~Base".into())),
        sig: FnSig {
            params: vec![],
            ret: v,
            cv: CvQual::default(),
            ref_q: None,
            variadic: false,
            noexcept: false,
        },
        virtuality: Virtuality::Virtual,
        vtable_index: None,
        special: Some(rustc_abi_cxx::SpecialMember::Dtor),
    };
    let base = c.define_class(ClassDef {
        name: NestedName(vec![NameSegment::Class(Ident("Base".into()))]),
        bases: vec![],
        fields: vec![],
        methods: vec![f_method.clone(), g_method.clone(), dtor_method.clone()],
        kind: RecordKind::Struct,
        is_polymorphic: true,
        is_final: false,
        source_alignment: None,
    });

    // Base::f(int) - virtual -> ?f@Base@@UEAAXH@Z
    assert_eq!(
        c.mangle_msvc(&Symbol::Method {
            class: base,
            name: MethodName::Ident(Ident("f".into())),
            sig: f_method.sig.clone(),
        }),
        "?f@Base@@UEAAXH@Z"
    );

    // Base::g() const - virtual -> ?g@Base@@UEBAHXZ
    assert_eq!(
        c.mangle_msvc(&Symbol::Method {
            class: base,
            name: MethodName::Ident(Ident("g".into())),
            sig: g_method.sig.clone(),
        }),
        "?g@Base@@UEBAHXZ"
    );

    // Base::~Base() - virtual -> ??1Base@@UEAA@XZ
    assert_eq!(
        c.mangle_msvc(&Symbol::Dtor {
            class: base,
            variant: DtorVariant::D1,
        }),
        "??1Base@@UEAA@XZ"
    );

    // struct Derived : Base — its dtor is implicitly virtual.
    let dtor_d = rustc_abi_cxx::MethodDef {
        name: MethodName::Ident(Ident("~Derived".into())),
        sig: FnSig {
            params: vec![],
            ret: v,
            cv: CvQual::default(),
            ref_q: None,
            variadic: false,
            noexcept: false,
        },
        virtuality: Virtuality::Virtual,
        vtable_index: None,
        special: Some(rustc_abi_cxx::SpecialMember::Dtor),
    };
    let derived = c.define_class(ClassDef {
        name: NestedName(vec![NameSegment::Class(Ident("Derived".into()))]),
        bases: vec![rustc_abi_cxx::BaseSpec {
            class: base,
            virtual_: false,
            access: rustc_abi_cxx::Access::Public,
        }],
        fields: vec![],
        methods: vec![f_method.clone(), g_method.clone(), dtor_d],
        kind: RecordKind::Struct,
        is_polymorphic: true,
        is_final: false,
        source_alignment: None,
    });

    // Derived::f(int) - virtual override -> ?f@Derived@@UEAAXH@Z
    assert_eq!(
        c.mangle_msvc(&Symbol::Method {
            class: derived,
            name: MethodName::Ident(Ident("f".into())),
            sig: f_method.sig.clone(),
        }),
        "?f@Derived@@UEAAXH@Z"
    );

    // Derived::~Derived() -> ??1Derived@@UEAA@XZ
    assert_eq!(
        c.mangle_msvc(&Symbol::Dtor {
            class: derived,
            variant: DtorVariant::D1,
        }),
        "??1Derived@@UEAA@XZ"
    );
}

// -------- mangle_substitutions (type + name back-refs) ---------------

const SUBS_EXPECTED: &[(&str, &str)] = &[
    // Two by-value V — top-level type back-ref fires.
    ("g_vv(V, V)", "?g_vv@@YAXUV@@0@Z"),
    // V then V& — different top-level types. Inner V name back-refs.
    ("g_vr(V, V&)", "?g_vr@@YAXUV@@AEAU1@@Z"),
    // Two V* — top-level type back-ref.
    ("g_pp(V*, V*)", "?g_pp@@YAXPEAUV@@0@Z"),
    // V*, V&, V — three different top-level types. Name back-refs
    // throughout.
    ("g_pvr(V*, V&, V)", "?g_pvr@@YAXPEAUV@@AEAU1@U1@@Z"),
    // int* repeated — top-level type back-ref on builtins-via-ptr.
    ("g_ipp(int*, int*)", "?g_ipp@@YAXPEAH0@Z"),
    ("g_ippp(int*, int*, int*)", "?g_ippp@@YAXPEAH00@Z"),
];

#[test]
fn msvc_substitutions_golden_has_expected_symbols() {
    let d = load("mangle_substitutions");
    assert_all_msvc(&d, SUBS_EXPECTED);
}

#[test]
fn msvc_substitutions_matches_clang() {
    fn ctx_with_v() -> (CxxTypeCtx, ClassId, TypeId, TypeId, TypeId, TypeId) {
        let mut c = ctx();
        let i = intern_int(&mut c, true, IntWidth::I32);
        let v_class = c.define_class(ClassDef {
            name: NestedName(vec![NameSegment::Class(Ident("V".into()))]),
            bases: vec![],
            fields: vec![],
            methods: vec![],
            kind: RecordKind::Struct,
            is_polymorphic: false,
            is_final: false,
            source_alignment: None,
        });
        let v_ty = c.intern_type(CxxType::Record(v_class));
        let v_ptr = c.intern_type(CxxType::Ptr { pointee: v_ty, cv: CvQual::default() });
        let v_ref = c.intern_type(CxxType::Ref {
            pointee: v_ty,
            kind: RefKind::Lvalue,
            cv: CvQual::default(),
        });
        (c, v_class, i, v_ty, v_ptr, v_ref)
    }

    fn mangle_free(c: &mut CxxTypeCtx, name: &str, params: Vec<TypeId>, ret: TypeId) -> String {
        let sig = FnSig {
            params,
            ret,
            cv: CvQual::default(),
            ref_q: None,
            variadic: false,
            noexcept: false,
        };
        c.mangle_msvc(&Symbol::Function {
            scope: NestedName(vec![]),
            name: Ident(name.into()),
            sig,
        })
    }

    // g_vv(V, V) → ?g_vv@@YAXUV@@0@Z
    {
        let (mut c, _, _, v_ty, _, _) = ctx_with_v();
        let v = intern_void(&mut c);
        assert_eq!(
            mangle_free(&mut c, "g_vv", vec![v_ty, v_ty], v),
            "?g_vv@@YAXUV@@0@Z"
        );
    }

    // g_vr(V, V&) → ?g_vr@@YAXUV@@AEAU1@@Z
    {
        let (mut c, _, _, v_ty, _, v_ref) = ctx_with_v();
        let v = intern_void(&mut c);
        assert_eq!(
            mangle_free(&mut c, "g_vr", vec![v_ty, v_ref], v),
            "?g_vr@@YAXUV@@AEAU1@@Z"
        );
    }

    // g_pp(V*, V*) → ?g_pp@@YAXPEAUV@@0@Z
    {
        let (mut c, _, _, _, v_ptr, _) = ctx_with_v();
        let v = intern_void(&mut c);
        assert_eq!(
            mangle_free(&mut c, "g_pp", vec![v_ptr, v_ptr], v),
            "?g_pp@@YAXPEAUV@@0@Z"
        );
    }

    // g_pvr(V*, V&, V) → ?g_pvr@@YAXPEAUV@@AEAU1@U1@@Z
    {
        let (mut c, _, _, v_ty, v_ptr, v_ref) = ctx_with_v();
        let v = intern_void(&mut c);
        assert_eq!(
            mangle_free(&mut c, "g_pvr", vec![v_ptr, v_ref, v_ty], v),
            "?g_pvr@@YAXPEAUV@@AEAU1@U1@@Z"
        );
    }

    // g_ipp(int*, int*) → ?g_ipp@@YAXPEAH0@Z
    {
        let mut c = ctx();
        let v = intern_void(&mut c);
        let i = intern_int(&mut c, true, IntWidth::I32);
        let ip = c.intern_type(CxxType::Ptr { pointee: i, cv: CvQual::default() });
        assert_eq!(
            mangle_free(&mut c, "g_ipp", vec![ip, ip], v),
            "?g_ipp@@YAXPEAH0@Z"
        );
    }

    // g_ippp(int*, int*, int*) → ?g_ippp@@YAXPEAH00@Z
    {
        let mut c = ctx();
        let v = intern_void(&mut c);
        let i = intern_int(&mut c, true, IntWidth::I32);
        let ip = c.intern_type(CxxType::Ptr { pointee: i, cv: CvQual::default() });
        assert_eq!(
            mangle_free(&mut c, "g_ippp", vec![ip, ip, ip], v),
            "?g_ippp@@YAXPEAH00@Z"
        );
    }
}

// -------- mangle_templates (class-template specializations) ----------

const TEMPLATES_EXPECTED: &[(&str, &str)] = &[
    // take_int_box(Box<int>) → `U?$Box@H@@`
    ("take_int_box(Box<int>)", "?take_int_box@@YAXU?$Box@H@@@Z"),
    // take_two(Box<int>, Box<int>) — second is type back-ref `0`.
    ("take_two(Box<int>, Box<int>)", "?take_two@@YAXU?$Box@H@@0@Z"),
    // take_int_and_float — different instantiations, no compression.
    (
        "take_int_and_float(Box<int>, Box<float>)",
        "?take_int_and_float@@YAXU?$Box@H@@U?$Box@M@@@Z",
    ),
];

#[test]
fn msvc_templates_golden_has_expected_symbols() {
    let d = load("mangle_templates");
    assert_all_msvc(&d, TEMPLATES_EXPECTED);
}

#[test]
fn msvc_templates_matches_clang() {
    fn make_ctx() -> (CxxTypeCtx, TypeId, TypeId, TypeId, TypeId) {
        let mut c = ctx();
        let v = intern_void(&mut c);
        let i = intern_int(&mut c, true, IntWidth::I32);
        let f = intern_float(&mut c, FloatKind::F32);
        // Two ClassDefs: Box<int> and Box<float>. Each carries the
        // TemplateSpec segment as its NestedName.
        let box_int = c.define_class(ClassDef {
            name: NestedName(vec![NameSegment::TemplateSpec {
                name: Ident("Box".into()),
                args: vec![TemplateArg::Type(i)],
            }]),
            bases: vec![],
            fields: vec![],
            methods: vec![],
            kind: RecordKind::Struct,
            is_polymorphic: false,
            is_final: false,
            source_alignment: None,
        });
        let box_float = c.define_class(ClassDef {
            name: NestedName(vec![NameSegment::TemplateSpec {
                name: Ident("Box".into()),
                args: vec![TemplateArg::Type(f)],
            }]),
            bases: vec![],
            fields: vec![],
            methods: vec![],
            kind: RecordKind::Struct,
            is_polymorphic: false,
            is_final: false,
            source_alignment: None,
        });
        let box_int_ty = c.intern_type(CxxType::Record(box_int));
        let box_float_ty = c.intern_type(CxxType::Record(box_float));
        (c, v, box_int_ty, box_float_ty, i)
    }

    // take_int_box(Box<int>)
    {
        let (mut c, v, box_int_ty, _, _) = make_ctx();
        let sig = FnSig {
            params: vec![box_int_ty],
            ret: v,
            cv: CvQual::default(),
            ref_q: None,
            variadic: false,
            noexcept: false,
        };
        assert_eq!(
            c.mangle_msvc(&Symbol::Function {
                scope: NestedName(vec![]),
                name: Ident("take_int_box".into()),
                sig,
            }),
            "?take_int_box@@YAXU?$Box@H@@@Z"
        );
    }

    // take_two(Box<int>, Box<int>) — back-ref `0` on second.
    {
        let (mut c, v, box_int_ty, _, _) = make_ctx();
        let sig = FnSig {
            params: vec![box_int_ty, box_int_ty],
            ret: v,
            cv: CvQual::default(),
            ref_q: None,
            variadic: false,
            noexcept: false,
        };
        assert_eq!(
            c.mangle_msvc(&Symbol::Function {
                scope: NestedName(vec![]),
                name: Ident("take_two".into()),
                sig,
            }),
            "?take_two@@YAXU?$Box@H@@0@Z"
        );
    }

    // take_int_and_float(Box<int>, Box<float>) — different types.
    {
        let (mut c, v, box_int_ty, box_float_ty, _) = make_ctx();
        let sig = FnSig {
            params: vec![box_int_ty, box_float_ty],
            ret: v,
            cv: CvQual::default(),
            ref_q: None,
            variadic: false,
            noexcept: false,
        };
        assert_eq!(
            c.mangle_msvc(&Symbol::Function {
                scope: NestedName(vec![]),
                name: Ident("take_int_and_float".into()),
                sig,
            }),
            "?take_int_and_float@@YAXU?$Box@H@@U?$Box@M@@@Z"
        );
    }
}

// -------- Itanium-vs-MSVC dispatcher round-trip -----------------------

#[test]
fn dispatcher_routes_on_abi_flavor() {
    // Same Symbol should mangle differently under the two flavors.
    let mut c_itanium = CxxTypeCtx::new(Target::x86_64_unknown_linux_gnu());
    let mut c_msvc = CxxTypeCtx::new(Target::x86_64_pc_windows_msvc());

    let i_itan = intern_int(&mut c_itanium, true, IntWidth::I32);
    let i_msvc = intern_int(&mut c_msvc, true, IntWidth::I32);
    let v_itan = intern_void(&mut c_itanium);
    let v_msvc = intern_void(&mut c_msvc);

    let sig_itan = FnSig {
        params: vec![i_itan],
        ret: v_itan,
        cv: CvQual::default(),
        ref_q: None,
        variadic: false,
        noexcept: false,
    };
    let sig_msvc = FnSig {
        params: vec![i_msvc],
        ret: v_msvc,
        cv: CvQual::default(),
        ref_q: None,
        variadic: false,
        noexcept: false,
    };

    let itan = c_itanium.mangle(&Symbol::Function {
        scope: NestedName(vec![]),
        name: Ident("foo".into()),
        sig: sig_itan,
    });
    let msvc = c_msvc.mangle(&Symbol::Function {
        scope: NestedName(vec![]),
        name: Ident("foo".into()),
        sig: sig_msvc,
    });
    // Itanium: `_Z3fooi` (with `v` as return). Actually wait — the
    // Itanium mangler doesn't encode the return type in free
    // functions. So `_Z3fooi`.
    assert_eq!(itan, "_Z3fooi");
    assert_eq!(msvc, "?foo@@YAXH@Z");

    // Round-trip through the explicit `_itanium` / `_msvc` entry
    // points returns the same strings.
    assert_eq!(
        itan,
        c_itanium.mangle_itanium(&Symbol::Function {
            scope: NestedName(vec![]),
            name: Ident("foo".into()),
            sig: FnSig {
                params: vec![i_itan],
                ret: v_itan,
                cv: CvQual::default(),
                ref_q: None,
                variadic: false,
                noexcept: false,
            },
        })
    );
}

// -------- Suppress unused imports for follow-up corpora ---------------
//
// These items will be used as the corpus grows; suppress dead-code
// warnings in the meantime.
#[allow(dead_code)]
fn _unused_imports_keepalive(
    _: Access,
    _: BaseSpec,
    _: ClassId,
    _: OperatorKind,
    _: Virtuality,
) {
}
